{% set version = "0.27.0" %}
{% set name = "ceu1kg" %}
{% set bioc = "3.12" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  md5: 49dcde1d1531a7e4cc8788f118d45050
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: SNPlocs.Hsapiens.dbSNP.20101109
requirements:
  host:
    - 'bioconductor-biobase >=2.50.0,<2.51.0'
    - 'bioconductor-ggbase >=3.52.0,<3.53.0'
    - 'bioconductor-ggtools >=5.25.0,<5.26.0'
    - r-base
  run:
    - 'bioconductor-biobase >=2.50.0,<2.51.0'
    - 'bioconductor-ggbase >=3.52.0,<3.53.0'
    - 'bioconductor-ggtools >=5.25.0,<5.26.0'
    - r-base
    - curl
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'CEU (N=60) genotypes from 1000 genomes pilot phase I'
  description: 'CEU genotypes from 1000 genomes "low coverage" pilot phase I (approx 8 million SNP calls released July 2010); includes Wellcome trust GENEVAR expression for 43 indiv'

