{% set version = "1.9.0" %}
{% set name = "rRDPData" %}
{% set bioc = "3.12" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 051ae4f29ea4820a1f06ff05bd63e42a
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# SystemRequirements: Java
requirements:
  host:
    - 'bioconductor-rrdp >=1.24.0,<1.25.0'
    - r-base
    - openjdk
  run:
    - 'bioconductor-rrdp >=1.24.0,<1.25.0'
    - r-base
    - curl
    - openjdk
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: GPL-2
  summary: 'Database for the Default RDP Classifier'
  description: 'Database used by the default RDP Classifier'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

