{% set name = "CellProfiler" %}
{% set version = "4.0.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/CellProfiler/{{ name  }}/archive/v{{ version }}.tar.gz
  sha256: "ba0a37f7c6602bdf6bc2ab16938845cc1ba9a4042e65b5273e0b9ee584678636"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed . -vv"
  #skip: True  # this is using for some reason up to 3GB of memory and crashes CCI, build and push locally
  #skip: True  # [win or osx or py3k]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python  >=3.8
    - pip
    - cython
    - openjdk
    - pytest
  run:
    - python  >=3.8
    - boto3
    - centrosome 
    - docutils
    - h5py  >=2.10
    - inflect
    - javabridge
    - joblib
    - mahotas
    - openjdk
    - matplotlib-base  >=2.0.0,<3
    - mysqlclient
    - numpy  >=1.16
    - prokaryote
    - python-bioformats
    - pyzmq
    - raven
    - requests
    - scikit-image  >=0.14
    - scikit-learn  >=0.20
    - scipy         >=1.2
    - six
    - future

test:
  imports:
    - cellprofiler

about:
  home: https://github.com/CellProfiler/CellProfiler
  license: 3-clause BSD
  license_family: BSD
  license_file: LICENSE
  summary: "CellProfiler is free, open-source software for quantitative analysis of biological images"
  description: |
     CellProfiler is free, open-source software for quantitative analysis of biological images.No prior experience in programming or computer vision is required.

extra:
  container:
    extended-base: true
  recipe-maintainers:
    - sunyi000
