{% set version = "1.40.0" %}
{% set name = "imageHTS" %}
{% set bioc = "3.12" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: ba2a998b5ae134239ecf976bbe965d57
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: BiocStyle, MASS
requirements:
  host:
    - 'bioconductor-biobase >=2.50.0,<2.51.0'
    - 'bioconductor-cellhts2 >=2.53.0,<2.54.0'
    - 'bioconductor-ebimage >=4.32.0,<4.33.0'
    - 'bioconductor-vsn >=3.58.0,<3.59.0'
    - r-base
    - r-e1071
    - r-hwriter
  run:
    - 'bioconductor-biobase >=2.50.0,<2.51.0'
    - 'bioconductor-cellhts2 >=2.53.0,<2.54.0'
    - 'bioconductor-ebimage >=4.32.0,<4.33.0'
    - 'bioconductor-vsn >=3.58.0,<3.59.0'
    - r-base
    - r-e1071
    - r-hwriter
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: LGPL-2.1
  summary: 'Analysis of high-throughput microscopy-based screens'
  description: 'imageHTS is an R package dedicated to the analysis of high-throughput microscopy-based screens. The package provides a modular and extensible framework to segment cells, extract quantitative cell features, predict cell types and browse screen data through web interfaces. Designed to operate in distributed environments, imageHTS provides a standardized access to remote data and facilitates the dissemination of high-throughput microscopy-based datasets.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-2.1'
extra:
  identifiers:
    - biotools:imagehts
    - doi:10.1038/nmeth.3252
  parent_recipe:
    name: bioconductor-imagehts
    path: recipes/bioconductor-imagehts
    version: 1.30.0

