{% set version = "1.33.0" %}

package:
  name: nanoplot
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nanoplot/NanoPlot-{{ version }}.tar.gz
  sha256: caf69a5789625e746814238cb4f0d510ed6768a094566e8f1dcaa77933c4d6fd

build:
  entry_points:
    - NanoPlot=nanoplot.NanoPlot:main
  number: 0
  noarch: python

requirements:
  host:
    - python >=3
    - setuptools
  run:
    - python >=3
    - biopython
    - pysam >0.10.0.0
    - pandas >=0.22.0
    - numpy
    - scipy
    - python-dateutil
    - seaborn >=0.10.1
    - nanoget >=1.14.0
    - nanomath >=1.0.0
    - pauvre >=0.2.0
    - plotly >=4.1.0
    - pyarrow
    - kaleido

test:
  imports:
    - nanoplot
  commands:
    - NanoPlot --help

about:
  home: https://github.com/wdecoster/NanoPlot
  license: GPL-3.0-only
  summary: 'Plotting suite for long read sequencing data and alignments'
  license_family: GPL
