{% set version = "1.17.0" %}
{% set name = "furrowSeg" %}
{% set bioc = "3.12" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 11a7a06520023de04b52125ae95a7df2
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: BiocStyle, ggplot2, knitr
requirements:
  host:
    - 'bioconductor-ebimage >=4.32.0,<4.33.0'
    - r-abind
    - r-base
    - r-dplyr
    - r-locfit
    - r-tiff
  run:
    - 'bioconductor-ebimage >=4.32.0,<4.33.0'
    - r-abind
    - r-base
    - r-dplyr
    - r-locfit
    - r-tiff
    - curl
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Furrow Segmentation'
  description: 'Image feature data and analysis codes for the Guglielmi, Barry et al. paper describing the application of an optogenetics tools to disrupt Drosophila embryo furrowing.'

