{% set version = "1.21.1" %}
{% set name = "gQTLBase" %}
{% set bioc = "3.12" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 2e5e749f3cea0b27eaeca82827f0d556
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: geuvStore2, knitr, rmarkdown, BiocStyle, RUnit, Homo.sapiens, IRanges, erma, GenomeInfoDb, gwascat, geuvPack
requirements:
  host:
    - 'bioconductor-biocgenerics >=0.36.0,<0.37.0'
    - 'bioconductor-genomicfiles >=1.26.0,<1.27.0'
    - 'bioconductor-genomicranges >=1.42.0,<1.43.0'
    - 'bioconductor-rtracklayer >=1.50.0,<1.51.0'
    - 'bioconductor-s4vectors >=0.28.0,<0.29.0'
    - 'bioconductor-summarizedexperiment >=1.20.0,<1.21.0'
    - r-base
    - r-batchjobs
    - r-bbmisc
    - r-bit
    - r-doparallel
    - r-ff
    - r-ffbase
    - r-foreach
  run:
    - 'bioconductor-biocgenerics >=0.36.0,<0.37.0'
    - 'bioconductor-genomicfiles >=1.26.0,<1.27.0'
    - 'bioconductor-genomicranges >=1.42.0,<1.43.0'
    - 'bioconductor-rtracklayer >=1.50.0,<1.51.0'
    - 'bioconductor-s4vectors >=0.28.0,<0.29.0'
    - 'bioconductor-summarizedexperiment >=1.20.0,<1.21.0'
    - r-base
    - r-batchjobs
    - r-bbmisc
    - r-bit
    - r-doparallel
    - r-ff
    - r-ffbase
    - r-foreach
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'gQTLBase: infrastructure for eQTL, mQTL and similar studies'
  description: 'Infrastructure for eQTL, mQTL and similar studies.'

