{% set version = "1.10.1" %}
{% set name = "Rbowtie2" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: e77f6fe7d54ae8b436e83efb7a92e17d0aa7a9c571f5c05030729496b7e367a7
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: knitr
# SystemRequirements: C++11
requirements:
  host:
    - r-base
    - libblas
    - liblapack
  run:
    - r-base
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 3)'
  summary: 'An R Wrapper for Bowtie2 and AdapterRemoval'
  description: 'This package provides an R wrapper of the popular bowtie2 sequencing reads aligner and AdapterRemoval, a convenient tool for rapid adapter trimming, identification, and read merging.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

