{% set version = "0.1.17" %}
{% set sha256 = "a77bdbc4ed41fa7570cfbb14b9802d974b38f30c3eade04d1a1244591b489df5" %}

package:
  name: "deeplc"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/d/deeplc/deeplc-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - deeplc=deeplc.__main__:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6,<3.8
  run:
    - matplotlib-base >=3,<4
    - numpy >=1.17,<1.19
    - opt-einsum >=2.3.2
    - pandas >=0.25,<1
    - python >=3.6,<3.8
    - scipy >=1.4.1
    - setuptools >=42.0.1
    - tensorflow >=1.14.0,<3

test:
  imports:
    - deeplc
  commands:
    - deeplc --help

about:
  home: http://compomics.github.io/projects/DeepLC
  license: Apache-2.0
  license_file: LICENSE
  license_family: APACHE
  summary: "DeepLC: Retention time prediction for (modified) peptides using Deep Learning."
  doc_url: http://compomics.github.io/projects/DeepLC
  dev_url: https://github.com/compomics/DeepLC

extra:
  recipe-maintainers:
    - compomics
