{% set name = "biobambam" %}
{% set version = "2.0.146" %}
{% set datestamp = "20191030105216" %}
{% set sha256hash = "438a8ce1c45f965efa0f93c847bf649fdb7a4c355228e9f24dfbeb18f344966d" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://gitlab.com/german.tischler/biobambam2/-/archive/{{ version }}-release-{{ datestamp }}/biobambam2-{{ version }}-release-{{ datestamp }}.tar.gz
  sha256: {{ sha256hash }}

build:
  number: 0
  binary_relocation: false
  skip: True  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - libmaus2
  run:
    - libmaus2

test:
  commands:
    - bamsormadup --help
    - bamtofastq --help
about:
  home: https://gitlab.com/german.tischler/biobambam2
  license: GPLv3
  summary: Tools for early stage alignment file processing
