{% set version = "1.2.2" %}
{% set name = "BiocSet" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 92816b3e786086603ecaacf1b18334520f4ed1d4334bc9b89c674f70f3c03010
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: GSEABase, airway, org.Hs.eg.db, DESeq2, limma, BiocFileCache, GO.db, testthat, knitr, rmarkdown, BiocStyle
requirements:
  host:
    - 'bioconductor-annotationdbi >=1.50.0,<1.51.0'
    - 'bioconductor-keggrest >=1.28.0,<1.29.0'
    - 'bioconductor-rtracklayer >=1.48.0,<1.49.0'
    - r-base
    - r-dplyr
    - r-plyr
    - r-rlang
    - r-tibble
  run:
    - 'bioconductor-annotationdbi >=1.50.0,<1.51.0'
    - 'bioconductor-keggrest >=1.28.0,<1.29.0'
    - 'bioconductor-rtracklayer >=1.48.0,<1.49.0'
    - r-base
    - r-dplyr
    - r-plyr
    - r-rlang
    - r-tibble
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Representing Different Biological Sets'
  description: 'BiocSet displays different biological sets in a triple tibble format. These three tibbles are `element`, `set`, and `elementset`. The user has the abilty to activate one of these three tibbles to perform common functions from the dplyr package. Mapping functionality and accessing web references for elements/sets are also available in BiocSet.'

