{% set version = "1.28.0" %}
{% set name = "shinyTANDEM" %}
{% set bioc = "3.12" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: d14dd9fb0d5f3c772ee1878ca2f0b4ba
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
requirements:
  host:
    - 'bioconductor-rtandem >=1.30.0,<1.31.0'
    - r-base
    - r-mixtools
    - r-shiny
    - r-xtable
  run:
    - 'bioconductor-rtandem >=1.30.0,<1.31.0'
    - r-base
    - r-mixtools
    - r-shiny
    - r-xtable
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'Provides a GUI for rTANDEM'
  description: 'This package provides a GUI interface for rTANDEM. The GUI is primarily designed to visualize rTANDEM result object or result xml files. But it will also provides an interface for creating parameter objects, launching searches or performing conversions between R objects and xml files.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
extra:
  parent_recipe:
    name: bioconductor-shinytandem
    path: recipes/bioconductor-shinytandem
    version: 1.20.0

