{% set name = "meryl" %}
{% set version = "1.1" %}
{% set sha256 = "9ec39535c6b565fcf2c3518f31c180b89b55dfaa8b1882fae84b928d12c70d11" %}

package:
  name: {{ name }}
  version: {{ version }}

about:
  home: 'https://github.com/marbl/meryl'
  summary: "meryl is a multi-threaded, multi-process, out-of-core k-mer counter"
  license: PUBLIC DOMAIN
  license_file: README.license

source:
  url: https://github.com/marbl/{{ name }}/archive/{{ version }}.tar.gz 
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True # [osx]

requirements:
  build:
    - {{ compiler('cxx') }}

test:
  commands:
    - "meryl 2>&1 | grep 'usage: meryl'"
    - "meryl-lookup 2>&1 | grep 'usage: meryl-lookup'"
    - "meryl-import 2>&1 | grep 'usage: meryl-import'"
    - "sequence 2>&1 | grep 'usage: sequence'"
