{% set version = "1.30.0" %}
{% set name = "HTSFilter" %}
{% set bioc = "3.12" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: a193e9de64a46d4a46e58e862b3071d7
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: EDASeq (>= 2.1.4), BiocStyle, testthat
requirements:
  host:
    - 'bioconductor-biobase >=2.50.0,<2.51.0'
    - 'bioconductor-biocparallel >=1.24.0,<1.25.0'
    - 'bioconductor-deseq >=1.42.0,<1.43.0'
    - 'bioconductor-deseq2 >=1.30.0,<1.31.0'
    - 'bioconductor-edger >=3.32.0,<3.33.0'
    - r-base
  run:
    - 'bioconductor-biobase >=2.50.0,<2.51.0'
    - 'bioconductor-biocparallel >=1.24.0,<1.25.0'
    - 'bioconductor-deseq >=1.42.0,<1.43.0'
    - 'bioconductor-deseq2 >=1.30.0,<1.31.0'
    - 'bioconductor-edger >=3.32.0,<3.33.0'
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Filter replicated high-throughput transcriptome sequencing data'
  description: 'This package implements a filtering procedure for replicated transcriptome sequencing data based on a global Jaccard similarity index in order to identify genes with low, constant levels of expression across one or more experimental conditions.'
extra:
  identifiers:
    - biotools:htsfilter
  parent_recipe:
    name: bioconductor-htsfilter
    path: recipes/bioconductor-htsfilter
    version: 1.20.0

