{% set version = "2.4.3" %}
{% set name = "ASICS" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: e0370099d0bb70ab2b8b3746ebd5eca3b2bf1b3ad731af3a580885c159af8e0e
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: knitr, rmarkdown, BiocStyle, testthat, ASICSdata
requirements:
  host:
    - 'bioconductor-biocparallel >=1.22.0,<1.23.0'
    - 'bioconductor-pepsnmr >=1.6.0,<1.7.0'
    - 'bioconductor-ropls >=1.20.0,<1.21.0'
    - 'bioconductor-summarizedexperiment >=1.18.0,<1.19.0'
    - r-base
    - r-ggplot2
    - r-gridextra
    - r-matrix
    - r-mvtnorm
    - r-plyr
    - r-quadprog
    - r-tsdist
    - r-zoo
  run:
    - 'bioconductor-biocparallel >=1.22.0,<1.23.0'
    - 'bioconductor-pepsnmr >=1.6.0,<1.7.0'
    - 'bioconductor-ropls >=1.20.0,<1.21.0'
    - 'bioconductor-summarizedexperiment >=1.18.0,<1.19.0'
    - r-base
    - r-ggplot2
    - r-gridextra
    - r-matrix
    - r-mvtnorm
    - r-plyr
    - r-quadprog
    - r-tsdist
    - r-zoo
  build:
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - xorg-libxfixes  # [linux]
test:
  commands:
    - 'LD_LIBRARY_PATH="${BUILD_PREFIX}/x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64" $R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'Automatic Statistical Identification in Complex Spectra'
  description: 'With a set of pure metabolite reference spectra, ASICS quantifies concentration of metabolites in a complex spectrum. The identification of metabolites is performed by fitting a mixture model to the spectra of the library with a sparse penalty. The method and its statistical properties are described in Tardivel et al. (2017) <doi:10.1007/s11306-017-1244-5>.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
extra:
  container:
    extended-base: true

