{% set version = "1.14.0" %}
{% set name = "msgbsR" %}
{% set bioc = "3.12" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: b1d28095cf464b352ad5e47f5b506d1b
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: roxygen2, BSgenome.Rnorvegicus.UCSC.rn6
requirements:
  host:
    - 'bioconductor-bsgenome >=1.58.0,<1.59.0'
    - 'bioconductor-easyrnaseq >=2.26.0,<2.27.0'
    - 'bioconductor-edger >=3.32.0,<3.33.0'
    - 'bioconductor-genomeinfodb >=1.26.0,<1.27.0'
    - 'bioconductor-genomicalignments >=1.26.0,<1.27.0'
    - 'bioconductor-genomicfeatures >=1.42.0,<1.43.0'
    - 'bioconductor-genomicranges >=1.42.0,<1.43.0'
    - 'bioconductor-ggbio >=1.38.0,<1.39.0'
    - 'bioconductor-iranges >=2.24.0,<2.25.0'
    - 'bioconductor-rsamtools >=2.6.0,<2.7.0'
    - 'bioconductor-s4vectors >=0.28.0,<0.29.0'
    - 'bioconductor-summarizedexperiment >=1.20.0,<1.21.0'
    - r-base
    - r-ggplot2
    - r-plyr
    - r-r.utils
  run:
    - 'bioconductor-bsgenome >=1.58.0,<1.59.0'
    - 'bioconductor-easyrnaseq >=2.26.0,<2.27.0'
    - 'bioconductor-edger >=3.32.0,<3.33.0'
    - 'bioconductor-genomeinfodb >=1.26.0,<1.27.0'
    - 'bioconductor-genomicalignments >=1.26.0,<1.27.0'
    - 'bioconductor-genomicfeatures >=1.42.0,<1.43.0'
    - 'bioconductor-genomicranges >=1.42.0,<1.43.0'
    - 'bioconductor-ggbio >=1.38.0,<1.39.0'
    - 'bioconductor-iranges >=2.24.0,<2.25.0'
    - 'bioconductor-rsamtools >=2.6.0,<2.7.0'
    - 'bioconductor-s4vectors >=0.28.0,<0.29.0'
    - 'bioconductor-summarizedexperiment >=1.20.0,<1.21.0'
    - r-base
    - r-ggplot2
    - r-plyr
    - r-r.utils
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'msgbsR: methylation sensitive genotyping by sequencing (MS-GBS) R functions'
  description: 'Pipeline for the anaysis of a MS-GBS experiment.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

