{% set version = "2.48.0" %}
{% set name = "rnaSeqMap" %}
{% set bioc = "3.12" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 7b922e6ec129d79364302f528934aeb3
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-biobase >=2.50.0,<2.51.0'
    - 'bioconductor-deseq >=1.42.0,<1.43.0'
    - 'bioconductor-edger >=3.32.0,<3.33.0'
    - 'bioconductor-genomicalignments >=1.26.0,<1.27.0'
    - 'bioconductor-genomicranges >=1.42.0,<1.43.0'
    - 'bioconductor-iranges >=2.24.0,<2.25.0'
    - 'bioconductor-rsamtools >=2.6.0,<2.7.0'
    - r-base
    - r-dbi
    - libblas
    - liblapack
  run:
    - 'bioconductor-biobase >=2.50.0,<2.51.0'
    - 'bioconductor-deseq >=1.42.0,<1.43.0'
    - 'bioconductor-edger >=3.32.0,<3.33.0'
    - 'bioconductor-genomicalignments >=1.26.0,<1.27.0'
    - 'bioconductor-genomicranges >=1.42.0,<1.43.0'
    - 'bioconductor-iranges >=2.24.0,<2.25.0'
    - 'bioconductor-rsamtools >=2.6.0,<2.7.0'
    - r-base
    - r-dbi
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'rnaSeq secondary analyses'
  description: 'The rnaSeqMap library provides classes and functions to analyze the RNA-sequencing data using the coverage profiles in multiple samples at a time'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
extra:
  identifiers:
    - biotools:rnaseqmap
    - doi:10.1186/1471-2105-12-200
  parent_recipe:
    name: bioconductor-rnaseqmap
    path: recipes/bioconductor-rnaseqmap
    version: 2.38.0

