{% set version = "1.6.3" %}
{% set name = "MSstatsTMT" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: d09dc9eaec97e2ffcecc6c57f5db746d94840a31dba3cd776f16afa99bd38cf7
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: BiocStyle, knitr, rmarkdown, testthat
requirements:
  host:
    - 'bioconductor-limma >=3.44.0,<3.45.0'
    - 'bioconductor-msstats >=3.20.0,<3.21.0'
    - r-base
    - r-data.table
    - r-dplyr
    - r-ggplot2
    - r-lme4
    - r-lmertest
    - r-matrixstats
    - r-reshape2
    - r-statmod
    - r-tidyr
  run:
    - 'bioconductor-limma >=3.44.0,<3.45.0'
    - 'bioconductor-msstats >=3.20.0,<3.21.0'
    - r-base
    - r-data.table
    - r-dplyr
    - r-ggplot2
    - r-lme4
    - r-lmertest
    - r-matrixstats
    - r-reshape2
    - r-statmod
    - r-tidyr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Protein Significance Analysis in shotgun mass spectrometry-based proteomic experiments with tandem mass tag (TMT) labeling'
  description: 'Tools for protein significance analysis in shotgun mass spectrometry-based proteomic experiments with tandem mass tag (TMT) labeling.'

