{% set version = "1.0.4" %}

package:
  name: ntjoin
  version: {{ version }}

source:
  url: https://github.com/bcgsc/ntJoin/releases/download/v{{ version }}/ntJoin-{{ version }}.tar.gz 
  sha256: 3d369ddc67573281cfe2361252f6839e5f0bfd110bbee0f13f2e3508a041800c 

build:
  number: 0
  skip: True  # [py<30]

requirements:
  build:
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - pip
    - zlib
  run:
    - python-igraph
    - pybedtools
    - pymannkendall
    - bedtools >=2.21.0
    - samtools
    - python
    - zlib
    - make

test:
  commands:
    - ntJoin help 

about:
  home: http://www.bcgsc.ca/platform/bioinfo/software/ntjoin
  license: GPL-3.0
  license_file: LICENSE
  summary: 'Genome assembly scaffolder using minimizer graphs'
