{% set version = "0.16.0" %}

package:
  name: pysam
  version: '{{ version }}'

source:
  url: https://github.com/pysam-developers/pysam/archive/v{{ version }}.tar.gz
  sha256: 07c9d3a772f90e9907a68bc3f495e2c608018a92888b9cf9f1197cb3a35aa9c3

build:
  number: 0 
  binary_relocation: False # [linux]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - python
    - setuptools
    - zlib
    - xz
    - bzip2
    - libdeflate
  run:
    - python
    - zlib
    - xz
    - bzip2
    - libdeflate
    - curl

test:
  imports:
    - pysam

about:
  home: https://github.com/pysam-developers/pysam
  license: MIT
  summary: "Pysam is a python module for reading and manipulating Samfiles. It is a lightweight wrapper of the samtools C-API. Pysam also includes an interface for tabix."

extra:
  identifiers:
    - biotools:pysam
    - doi:10.1093/bioinformatics/btp352
