{% set name = "smof" %}
{% set version = "2.21.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "3d1708eb60038b20da18da96471361a6ee20ce94560fd2172b830ee3d1fd5222"

build:
  noarch: python
  number: 0
  entry_points:
    - smof=smof.main:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >3
  run:
    - python >3

test:
  imports:
    - smof
  commands:
    - smof --help

about:
  home: "https://github.com/incertae-sedis/smof"
  license: "MIT"
  summary: "UNIX-style utilities for FASTA file exploration"
  
extra:
  recipe-maintainers:
   - arendsee
