{% set version = "2.16" %}

package:
  name: dunovo
  version: {{ version }}

source:
  url: https://github.com/galaxyproject/dunovo/archive/v{{ version }}.tar.gz
  sha256: e2594064fbc20a395a12a5f2d48bf9e5105947878477aa304e4b4c127b7818de

build:
  number: 0
  skip: True  # [py27]

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - python
    - wget

  run:
    - python
    - mafft 7.271
    - bowtie >=1.1.2
    - networkx >=2.4
    - paste
    - gawk

test:
  commands:
    - 'correct.py --version > /dev/null'
    - 'align-families.py --version > /dev/null'
    - 'make-consensi.py --version > /dev/null'
    - 'precheck.py --help > /dev/null'
    - 'trimmer.py --help > /dev/null'
  imports:
    - networkx

about:
  home: https://github.com/galaxyproject/dunovo
  license: GPLv2
  license_file: LICENSE.txt
  summary: "Du Novo: A pipeline for processing duplex sequencing data."
