{% set version = "1.2.0" %}
{% set name = "tscR" %}
{% set bioc = "3.12" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: ec418fc28b2c5cb98b666fe37cb64d88
build:
  number: 0
  skip: True  # [osx]
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: testthat
requirements:
  host:
    - 'bioconductor-genomicranges >=1.42.0,<1.43.0'
    - 'bioconductor-iranges >=2.24.0,<2.25.0'
    - 'bioconductor-s4vectors >=0.28.0,<0.29.0'
    - 'bioconductor-summarizedexperiment >=1.20.0,<1.21.0'
    - r-base
    - r-class
    - r-cluster
    - r-dplyr
    - r-dtw
    - r-ggplot2
    - r-gridextra
    - r-kmlshape
    - r-knitr
    - r-latex2exp
    - r-prettydoc
    - r-rcolorbrewer
    - r-rmarkdown
    - libblas
    - liblapack
  run:
    - 'bioconductor-genomicranges >=1.42.0,<1.43.0'
    - 'bioconductor-iranges >=2.24.0,<2.25.0'
    - 'bioconductor-s4vectors >=0.28.0,<0.29.0'
    - 'bioconductor-summarizedexperiment >=1.20.0,<1.21.0'
    - r-base
    - r-class
    - r-cluster
    - r-dplyr
    - r-dtw
    - r-ggplot2
    - r-gridextra
    - r-kmlshape
    - r-knitr
    - r-latex2exp
    - r-prettydoc
    - r-rcolorbrewer
    - r-rmarkdown
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>=2)'
  summary: 'A time series clustering package combining slope and Frechet distances'
  description: 'Clustering for time series data using slope distance and/or shape distance.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
extra:
  container:
    extended-base: true

