{% set version = "1.8.3" %}
{% set name = "rWikiPathways" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 68f407b04d4e3adeb446a581e5c7f87567ec30f8ad0b2dcd97ced1f1abadb27a
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: testthat, BiocStyle, knitr, rmarkdown
requirements:
  host:
    - r-base
    - r-data.table
    - r-httr
    - r-rjson
    - r-tidyr
    - r-xml
  run:
    - r-base
    - r-data.table
    - r-httr
    - r-rjson
    - r-tidyr
    - r-xml
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'MIT + file LICENSE'
  summary: 'rWikiPathways - R client library for the WikiPathways API'
  description: 'Use this package to interface with the WikiPathways API.'
  license_file: LICENSE

