package:
  name: perl-sanger-cgp-allelecount
  version: '4.2.0'

source:
  url: https://github.com/cancerit/alleleCount/archive/v4.2.0.tar.gz
  sha256: df5be9b4d2027f9228d59f4b9dbe7e416b8a5cf1bf4597418afb44662530142c

build:
  number: 0
  skip: True # [osx]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - perl
    - perl-app-cpanminus
    - perl-module-build
    - perl-sanger-cgp-vcf
    - perl-bio-samtools
    - perl-bioperl
  run:
    - perl
    - perl-sanger-cgp-vcf
    - perl-bio-samtools
    - perl-bioperl
    - perl-devel-cover

test:
  imports:
    - Sanger::CGP::AlleleCount

about:
  home: https://github.com/cancerit/alleleCount
  license: GPLv3
  summary: Support code for NGS copy number algorithm
