{% set version = "1.2.1" %}
{% set name = "OmnipathR" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: e800093a498db9829ffc54e44aee3307a781f9f5cdab44c5d7b5d009549a782c
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: tidyr, dnet, gprofiler2, BiocStyle, testthat, knitr, rmarkdown, ggplot2, ggraph
requirements:
  host:
    - r-base
    - r-dplyr
    - r-igraph
    - r-rlang
  run:
    - r-base
    - r-dplyr
    - r-igraph
    - r-rlang
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'MIT + file LICENSE'
  summary: 'Import Omnipath network'
  description: 'Import data from https://www.omnipathdb.org webservice. It also includes functions to transform and print this data.'
  license_file: LICENSE

