{% set version = "1.8.2" %}
{% set name = "igvR" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 9769e04c22b621864fdb68fbd6b79d720293ec9e841c3fa228793ff0b1cdfd28
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: RUnit, BiocStyle, knitr, rmarkdown
requirements:
  host:
    - 'bioconductor-biocgenerics >=0.34.0,<0.35.0'
    - 'bioconductor-browserviz >=2.10.0,<2.11.0'
    - 'bioconductor-genomicalignments >=1.24.0,<1.25.0'
    - 'bioconductor-genomicranges >=1.40.0,<1.41.0'
    - 'bioconductor-motifdb >=1.30.0,<1.31.0'
    - 'bioconductor-rtracklayer >=1.48.0,<1.49.0'
    - 'bioconductor-seqlogo >=1.54.0,<1.55.0'
    - 'bioconductor-variantannotation >=1.34.0,<1.35.0'
    - r-base
    - r-httpuv
    - r-rcolorbrewer
  run:
    - 'bioconductor-biocgenerics >=0.34.0,<0.35.0'
    - 'bioconductor-browserviz >=2.10.0,<2.11.0'
    - 'bioconductor-genomicalignments >=1.24.0,<1.25.0'
    - 'bioconductor-genomicranges >=1.40.0,<1.41.0'
    - 'bioconductor-motifdb >=1.30.0,<1.31.0'
    - 'bioconductor-rtracklayer >=1.48.0,<1.49.0'
    - 'bioconductor-seqlogo >=1.54.0,<1.55.0'
    - 'bioconductor-variantannotation >=1.34.0,<1.35.0'
    - r-base
    - r-httpuv
    - r-rcolorbrewer
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'MIT + file LICENSE'
  summary: 'igvR: integrative genomics viewer'
  description: 'Access to igv.js, the Integrative Genomics Viewer running in a web browser.'
  license_file: LICENSE

