{% set version = "1.14.0" %}
{% set name = "coseq" %}
{% set bioc = "3.12" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  md5: a977cf445a6eb040d1e1c6c1280676bc
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: Biobase, knitr, rmarkdown, testthat
requirements:
  host:
    - 'bioconductor-biocparallel >=1.24.0,<1.25.0'
    - 'bioconductor-deseq2 >=1.30.0,<1.31.0'
    - 'bioconductor-edger >=3.32.0,<3.33.0'
    - 'bioconductor-htsfilter >=1.30.0,<1.31.0'
    - 'bioconductor-s4vectors >=0.28.0,<0.29.0'
    - 'bioconductor-summarizedexperiment >=1.20.0,<1.21.0'
    - r-base
    - r-capushe
    - r-compositions
    - r-corrplot
    - r-e1071
    - 'r-ggplot2 >=2.1.0'
    - 'r-htscluster >=2.0.8'
    - r-mvtnorm
    - r-rmixmod
    - r-scales
  run:
    - 'bioconductor-biocparallel >=1.24.0,<1.25.0'
    - 'bioconductor-deseq2 >=1.30.0,<1.31.0'
    - 'bioconductor-edger >=3.32.0,<3.33.0'
    - 'bioconductor-htsfilter >=1.30.0,<1.31.0'
    - 'bioconductor-s4vectors >=0.28.0,<0.29.0'
    - 'bioconductor-summarizedexperiment >=1.20.0,<1.21.0'
    - r-base
    - r-capushe
    - r-compositions
    - r-corrplot
    - r-e1071
    - 'r-ggplot2 >=2.1.0'
    - 'r-htscluster >=2.0.8'
    - r-mvtnorm
    - r-rmixmod
    - r-scales
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>=3)'
  summary: 'Co-Expression Analysis of Sequencing Data'
  description: 'Co-expression analysis for expression profiles arising from high-throughput sequencing data. Feature (e.g., gene) profiles are clustered using adapted transformations and mixture models or a K-means algorithm, and model selection criteria (to choose an appropriate number of clusters) are provided.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

