{% set version = "0.5.1" %}
{% set sha256 = "7fd1529e55cbb648224e80f1c2636f568d757f2da13777dc2186a2aa7d67e067" %}

package:
  name: perbase
  version: {{ version }}

source:
  url: https://github.com/sstadick/perbase/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - rust >=1.42
    - clangdev
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - curl
    - openssl
    - zlib
    - bzip2
    - xz
    - clangdev
  run:
    - curl
    - openssl
    - zlib
    - bzip2
    - xz

test:
  commands:
    - perbase --help

about:
  home: https://github.com/sstadick/perbase
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Per-base metrics on BAM/CRAM files.
