{% set version = "1.4.0" %}
{% set name = "APAlyzer" %}
{% set bioc = "3.12" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 25b1ffe4ca0418c58094b0265653d3c8
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: knitr, rmarkdown, BiocStyle, org.Mm.eg.db, AnnotationDbi, TBX20BamSubset, Rsamtools, testthat
requirements:
  host:
    - 'bioconductor-deseq >=1.42.0,<1.43.0'
    - 'bioconductor-ensembldb >=2.14.0,<2.15.0'
    - 'bioconductor-genomicalignments >=1.26.0,<1.27.0'
    - 'bioconductor-genomicfeatures >=1.42.0,<1.43.0'
    - 'bioconductor-genomicranges >=1.42.0,<1.43.0'
    - 'bioconductor-rsubread >=2.4.0,<2.5.0'
    - 'bioconductor-rtracklayer >=1.50.0,<1.51.0'
    - 'bioconductor-summarizedexperiment >=1.20.0,<1.21.0'
    - 'bioconductor-variantannotation >=1.36.0,<1.37.0'
    - r-base
    - r-dplyr
    - r-ggplot2
    - r-ggrepel
    - r-repmis
    - r-tidyr
  run:
    - 'bioconductor-deseq >=1.42.0,<1.43.0'
    - 'bioconductor-ensembldb >=2.14.0,<2.15.0'
    - 'bioconductor-genomicalignments >=1.26.0,<1.27.0'
    - 'bioconductor-genomicfeatures >=1.42.0,<1.43.0'
    - 'bioconductor-genomicranges >=1.42.0,<1.43.0'
    - 'bioconductor-rsubread >=2.4.0,<2.5.0'
    - 'bioconductor-rtracklayer >=1.50.0,<1.51.0'
    - 'bioconductor-summarizedexperiment >=1.20.0,<1.21.0'
    - 'bioconductor-variantannotation >=1.36.0,<1.37.0'
    - r-base
    - r-dplyr
    - r-ggplot2
    - r-ggrepel
    - r-repmis
    - r-tidyr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: LGPL-3
  summary: 'A toolkit for APA analysis using RNA-seq data'
  description: 'Perform 3''UTR APA, Intronic APA and gene expression analysis using RNA-seq data.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3'

