{% set version = "1.18.1" %}
{% set name = "sevenbridges" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 09c6492a848c34d9d71c782f379350dcd1a855a5528c9f654dae07faae3ba5b6
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: knitr, rmarkdown, testthat, readr
requirements:
  host:
    - 'bioconductor-s4vectors >=0.26.0,<0.27.0'
    - r-base
    - r-curl
    - r-docopt
    - r-dplyr
    - r-httr
    - r-jsonlite
    - r-objectproperties
    - r-stringr
    - r-uuid
    - r-yaml
  run:
    - 'bioconductor-s4vectors >=0.26.0,<0.27.0'
    - r-base
    - r-curl
    - r-docopt
    - r-dplyr
    - r-httr
    - r-jsonlite
    - r-objectproperties
    - r-stringr
    - r-uuid
    - r-yaml
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'Apache License 2.0 | file LICENSE'
  summary: 'Seven Bridges Platform API Client and Common Workflow Language Tool Builder in R'
  description: 'R client and utilities for Seven Bridges platform API, from Cancer Genomics Cloud to other Seven Bridges supported platforms.'
  license_file: LICENSE

