{% set version = "0.19.0" %}
{% set name = "yriMulti" %}
{% set bioc = "3.12" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 1be47b590d01aa030ffae8e32754c23b
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: erma, BiocStyle, knitr, rmarkdown, gQTLstats (>= 1.9.2), doParallel, geuvPack, knitcitations, bibtex
requirements:
  host:
    - 'bioconductor-dsqtl >=0.28.0,<0.29.0'
    - 'bioconductor-genomeinfodb >=1.26.0,<1.27.0'
    - 'bioconductor-genomicfiles >=1.26.0,<1.27.0'
    - 'bioconductor-genomicranges >=1.42.0,<1.43.0'
    - 'bioconductor-geuvpack >=1.22.0,<1.23.0'
    - 'bioconductor-gqtlbase >=1.21.0,<1.22.0'
    - 'bioconductor-homo.sapiens >=1.3.0,<1.4.0'
    - 'bioconductor-multiassayexperiment >=1.16.0,<1.17.0'
    - 'bioconductor-summarizedexperiment >=1.20.0,<1.21.0'
    - 'bioconductor-variantannotation >=1.36.0,<1.37.0'
    - r-base
  run:
    - 'bioconductor-dsqtl >=0.28.0,<0.29.0'
    - 'bioconductor-genomeinfodb >=1.26.0,<1.27.0'
    - 'bioconductor-genomicfiles >=1.26.0,<1.27.0'
    - 'bioconductor-genomicranges >=1.42.0,<1.43.0'
    - 'bioconductor-geuvpack >=1.22.0,<1.23.0'
    - 'bioconductor-gqtlbase >=1.21.0,<1.22.0'
    - 'bioconductor-homo.sapiens >=1.3.0,<1.4.0'
    - 'bioconductor-multiassayexperiment >=1.16.0,<1.17.0'
    - 'bioconductor-summarizedexperiment >=1.20.0,<1.21.0'
    - 'bioconductor-variantannotation >=1.36.0,<1.37.0'
    - r-base
    - curl
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'support for expression, methylation, DHS, VCF for YRI'
  description: 'expression, methylation, DHS for YRI'

