{% set version = "0.9.0" %}
{% set sha256 = "1c07280c3b76cdb05689f4b1fc78da275f96e69e33eda3a557a3c196ab359f55" %}

package:
  name: taxtastic
  version: '{{version}}'

source:
  url: https://pypi.python.org/packages/source/t/taxtastic/taxtastic-{{version}}.tar.gz
  sha256: '{{sha256}}'

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python >3
    - setuptools
    - sqlalchemy >=0.7
    - decorator
    - biopython
    - xlrd

  run:
    - python >3
    - sqlalchemy >=0.7
    - decorator
    - biopython
    - xlrd

test:
  imports:
    - taxtastic
    - taxtastic.scripts
    - taxtastic.subcommands

about:
  home: https://github.com/fhcrc/taxtastic
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Tools for taxonomic naming and annotation
