{% set version = "1.1.alpha17" %}
{% set sha256 = "db1ac64e1bc9b4d24d17ee2e388c061c283ca9fbec075e022bdeaad1adc6d41c" %}

package:
  name: pplacer
  version: '{{ version }}'

source:
  url: https://github.com/matsen/pplacer/releases/download/v{{ version }}/pplacer-Darwin-v{{ version }}.zip
  sha256: '{{ sha256 }}'

build:
  skip: true   # [linux]
  number: 1

requirements:
  host:
    - gsl
  run:
    - gsl
    
test:
  commands:
    - pplacer --help > /dev/null
    - guppy to_csv --help > /dev/null
    - rppr check --help > /dev/null

about:
  home: http://matsen.fredhutch.org/pplacer/
  license: GPL-3.0
  license_family: GPL
  summary: Pplacer places query sequences on a fixed reference phylogenetic tree to
    maximize phylogenetic likelihood or posterior probability according to a reference
    alignment.
  dev_url: https://github.com/matsen/pplacer/

extra:
  skip-lints:
    - should_be_noarch_generic
