{% set version = "4.24.2" %}
{% set name = "PWMEnrich" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: a4964b3faca0cd697971627cb3b7c4c2bf7d65d357329461af5ed82638833e3f
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: MotifDb, BSgenome.Dmelanogaster.UCSC.dm3, PWMEnrich.Dmelanogaster.background, testthat, gtools, parallel, PWMEnrich.Hsapiens.background, PWMEnrich.Mmusculus.background, BiocStyle, knitr
requirements:
  host:
    - 'bioconductor-biocgenerics >=0.34.0,<0.35.0'
    - 'bioconductor-biostrings >=2.56.0,<2.57.0'
    - 'bioconductor-seqlogo >=1.54.0,<1.55.0'
    - r-base
    - r-evd
    - r-gdata
  run:
    - 'bioconductor-biocgenerics >=0.34.0,<0.35.0'
    - 'bioconductor-biostrings >=2.56.0,<2.57.0'
    - 'bioconductor-seqlogo >=1.54.0,<1.55.0'
    - r-base
    - r-evd
    - r-gdata
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'LGPL (>= 2)'
  summary: 'PWM enrichment analysis'
  description: 'A toolkit of high-level functions for DNA motif scanning and enrichment analysis built upon Biostrings. The main functionality is PWM enrichment analysis of already known PWMs (e.g. from databases such as MotifDb), but the package also implements high-level functions for PWM scanning and visualisation. The package does not perform "de novo" motif discovery, but is instead focused on using motifs that are either experimentally derived or computationally constructed by other tools.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3'
extra:
  identifiers:
    - biotools:pwmenrich
    - doi:10.1038/nmeth.3252
  parent_recipe:
    name: bioconductor-pwmenrich
    path: recipes/bioconductor-pwmenrich
    version: 4.16.0

