{% set version = "1.22.1" %}
{% set name = "mogsa" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 7f5bc4033d69658eb4a6d353fa583aaa7e7f42d8af23c6de584c9bce8c04f13f
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: BiocStyle, knitr, org.Hs.eg.db
requirements:
  host:
    - 'bioconductor-biobase >=2.48.0,<2.49.0'
    - 'bioconductor-biocgenerics >=0.34.0,<0.35.0'
    - 'bioconductor-genefilter >=1.70.0,<1.71.0'
    - 'bioconductor-graphite >=1.34.0,<1.35.0'
    - 'bioconductor-gseabase >=1.50.0,<1.51.0'
    - r-base
    - r-cluster
    - r-corpcor
    - r-gplots
    - r-svd
  run:
    - 'bioconductor-biobase >=2.48.0,<2.49.0'
    - 'bioconductor-biocgenerics >=0.34.0,<0.35.0'
    - 'bioconductor-genefilter >=1.70.0,<1.71.0'
    - 'bioconductor-graphite >=1.34.0,<1.35.0'
    - 'bioconductor-gseabase >=1.50.0,<1.51.0'
    - r-base
    - r-cluster
    - r-corpcor
    - r-gplots
    - r-svd
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'Multiple omics data integrative clustering and gene set analysis'
  description: 'This package provide a method for doing gene set analysis based on multiple omics data.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

