{% set version = "1.6.1" %}
{% set name = "consensus" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 9e1ad0f229ad94eb2729a6ce04f59f78cb16d044c416529eac1b7abc01c4091c
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: knitr, RUnit, rmarkdown, BiocGenerics
requirements:
  host:
    - r-base
    - r-gplots
    - r-matrixstats
    - r-rcolorbrewer
  run:
    - r-base
    - r-gplots
    - r-matrixstats
    - r-rcolorbrewer
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'BSD_3_clause + file LICENSE'
  summary: 'Cross-platform consensus analysis of genomic measurements via interlaboratory testing method'
  description: 'An implementation of the American Society for Testing and Materials (ASTM) Standard E691 for interlaboratory testing procedures, designed for cross-platform genomic measurements. Given three (3) or more genomic platforms or laboratory protocols, this package provides interlaboratory testing procedures giving per-locus comparisons for sensitivity and precision between platforms.'
  license_file: LICENSE
extra:
  parent_recipe:
    name: bioconductor-consensus
    path: recipes/bioconductor-consensus
    version: 1.0.0

