{% set version = "2.38.0" %}
{% set name = "RNAither" %}
{% set bioc = "3.12" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 3ea77d6fc60a4e23a4dbcc8b694d6002
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
requirements:
  host:
    - 'bioconductor-biomart >=2.46.0,<2.47.0'
    - 'bioconductor-geneplotter >=1.68.0,<1.69.0'
    - 'bioconductor-limma >=3.46.0,<3.47.0'
    - 'bioconductor-prada >=1.66.0,<1.67.0'
    - 'bioconductor-rankprod >=3.16.0,<3.17.0'
    - 'bioconductor-splots >=1.56.0,<1.57.0'
    - 'bioconductor-topgo >=2.41.0,<2.42.0'
    - r-base
    - r-car
  run:
    - 'bioconductor-biomart >=2.46.0,<2.47.0'
    - 'bioconductor-geneplotter >=1.68.0,<1.69.0'
    - 'bioconductor-limma >=3.46.0,<3.47.0'
    - 'bioconductor-prada >=1.66.0,<1.67.0'
    - 'bioconductor-rankprod >=3.16.0,<3.17.0'
    - 'bioconductor-splots >=1.56.0,<1.57.0'
    - 'bioconductor-topgo >=2.41.0,<2.42.0'
    - r-base
    - r-car
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Statistical analysis of high-throughput RNAi screens'
  description: 'RNAither analyzes cell-based RNAi screens, and includes quality assessment, customizable normalization and statistical tests, leading to lists of significant genes and biological processes.'
extra:
  identifiers:
    - biotools:rnaither
    - doi:10.1093/bioinformatics/btp014
  parent_recipe:
    name: bioconductor-rnaither
    path: recipes/bioconductor-rnaither
    version: 2.28.0

