{% set version = "1.30.0" %}
{% set name = "metaseqR" %}
{% set bioc = "3.12" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 98302550242e550aae10ee42d48bc5b5
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: BiocGenerics, GenomicRanges, rtracklayer, Rsamtools, survcomp, VennDiagram, knitr, zoo, RUnit, BiocManager, BSgenome, RSQLite
requirements:
  host:
    - 'bioconductor-bayseq >=2.24.0,<2.25.0'
    - 'bioconductor-biomart >=2.46.0,<2.47.0'
    - 'bioconductor-deseq >=1.42.0,<1.43.0'
    - 'bioconductor-edaseq >=2.24.0,<2.25.0'
    - 'bioconductor-edger >=3.32.0,<3.33.0'
    - 'bioconductor-limma >=3.46.0,<3.47.0'
    - 'bioconductor-noiseq >=2.34.0,<2.35.0'
    - 'bioconductor-qvalue >=2.22.0,<2.23.0'
    - 'bioconductor-vsn >=3.58.0,<3.59.0'
    - r-base
    - r-brew
    - r-corrplot
    - r-gplots
    - r-log4r
    - r-nbpseq
    - r-rjson
  run:
    - 'bioconductor-bayseq >=2.24.0,<2.25.0'
    - 'bioconductor-biomart >=2.46.0,<2.47.0'
    - 'bioconductor-deseq >=1.42.0,<1.43.0'
    - 'bioconductor-edaseq >=2.24.0,<2.25.0'
    - 'bioconductor-edger >=3.32.0,<3.33.0'
    - 'bioconductor-limma >=3.46.0,<3.47.0'
    - 'bioconductor-noiseq >=2.34.0,<2.35.0'
    - 'bioconductor-qvalue >=2.22.0,<2.23.0'
    - 'bioconductor-vsn >=3.58.0,<3.59.0'
    - r-base
    - r-brew
    - r-corrplot
    - r-gplots
    - r-log4r
    - r-nbpseq
    - r-rjson
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 3)'
  summary: 'An R package for the analysis and result reporting of RNA-Seq data by combining multiple statistical algorithms.'
  description: 'Provides an interface to several normalization and statistical testing packages for RNA-Seq gene expression data. Additionally, it creates several diagnostic plots, performs meta-analysis by combinining the results of several statistical tests and reports the results in an interactive way.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

