{% set version = "0.5.0" %}
{% set sha256 = "2e624682f690e81c877e6eb3ea4bcae217d8f5ce47435247158b448a843f1143" %}


package:
  name: EnrichM
  version: {{ version }}

source:
  url: https://github.com/geronimp/enrichM/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"



requirements:
  host:
    - python >3.6,<3.8
    - pip

  run:
    - hmmer >= 3.1b
    - diamond = 0.9.22
    - prodigal >= 2.6.3
    - parallel >= 20180222
    - mmseqs >= 2-23394
    - R >= 3.0.1
    - mcl >= 14-137
    - r-gridExtra
    - r-optparse

test:
  commands:
    - enrichm --help

about:
  home: https://github.com/geronimp/enrichM
  dev_url: https://github.com/geronimp/enrichM
  doc_url: https://github.com/geronimp/enrichM/wiki
  license: GNU GPL v3+
  license_family: GLP


extra:
  recipe-maintainers:
    - silask
    - geronimp
