{% set version = "1.0.2" %}
{% set sha256 = "06f066b8202e4472d44cb074de724024095ac724a44e208328d1cf0ddc76e828" %}

package:
  name: mirfix
  version: '{{version}}'

source:
  url: https://github.com/Bierinformatik/MIRfix/archive/v{{ version }}.tar.gz
  sha256: '{{sha256}}'

build:
  noarch: python
  number: 0

requirements:
  host:
    - python <3
  run:
    - python <3
    - biopython
    - tk
    - numpy
    - matplotlib
    - viennarna
    - dialign2
    - clustalw

test:
  imports:
    - RNA
  commands:
    - MIRfix.py --help

about:
  home: https://github.com/Bierinformatik/MIRfix
  license: GPL-3.0
  license_family: GPL
  summary: MIRfix automatically curates miRNA datasets by improving alignments of their precursors, the consistency of the annotation of mature miR and miR* sequence, and the phylogenetic coverage. MIRfix produces alignments that are comparable across families and sets the stage for improved homology search as well as quantitative analyses.
