{% set version = "1.4.2" %}
{% set name = "sitePath" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 2dd3087867e50acd0fc9fbc468970b1382d083b0c53fc5c745961f3976e180d8
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: testthat, knitr, rmarkdown, BiocStyle
requirements:
  host:
    - r-ape
    - r-base
    - r-rcpp
    - r-seqinr
    - libblas
    - liblapack
  run:
    - r-ape
    - r-base
    - r-rcpp
    - r-seqinr
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'MIT + file LICENSE'
  summary: 'Detection of sites with fixation of amino acid substitutions in protein evolution'
  description: 'The package does hierarchical search for fixation events given multiple sequence alignment and phylogenetic tree. These fixation events can be specific to a phylogenetic lineages or shared by multiple lineages.'
  license_file: LICENSE

