{% set version = "0.13.1" %}
{% set sha256 = "357addd8527a57ba5b0eb32df7acef089f268abf5bf8e2fb0ce9cf20c4463065" %}

package:
  name: vcfpy
  version: '{{version}}'

source:
  url: https://pypi.io/packages/source/v/vcfpy/vcfpy-{{version}}.tar.gz
  sha256: '{{sha256}}'

build:
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python
  number: 0

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - pysam >=0.10.0

test:
  imports:
    - vcfpy

about:
  home: https://github.com/bihealth/vcfpy
  license: MIT
  license_family: MIT
  summary: Python 3 VCF library with good support for both reading and writing
