{% set version = "3.16.2" %}
{% set name = "TPP" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 7806231d91908f778fd219ecde003802a2441b4a91d729bb430005002cdd5e0c
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: BiocStyle, testthat
requirements:
  host:
    - 'bioconductor-biobase >=2.48.0,<2.49.0'
    - 'bioconductor-biobroom >=1.20.0,<1.21.0'
    - 'bioconductor-limma >=3.44.0,<3.45.0'
    - r-base
    - r-broom
    - r-data.table
    - r-doparallel
    - r-dplyr
    - r-foreach
    - r-futile.logger
    - r-ggplot2
    - r-gridextra
    - r-knitr
    - r-magrittr
    - r-mass
    - r-mefa
    - r-nls2
    - 'r-openxlsx >=2.4.0'
    - r-plyr
    - r-purrr
    - r-rcolorbrewer
    - r-rcurl
    - r-reshape2
    - r-rmarkdown
    - r-stringr
    - r-tidyr
    - r-venndiagram
    - r-vgam
  run:
    - 'bioconductor-biobase >=2.48.0,<2.49.0'
    - 'bioconductor-biobroom >=1.20.0,<1.21.0'
    - 'bioconductor-limma >=3.44.0,<3.45.0'
    - r-base
    - r-broom
    - r-data.table
    - r-doparallel
    - r-dplyr
    - r-foreach
    - r-futile.logger
    - r-ggplot2
    - r-gridextra
    - r-knitr
    - r-magrittr
    - r-mass
    - r-mefa
    - r-nls2
    - 'r-openxlsx >=2.4.0'
    - r-plyr
    - r-purrr
    - r-rcolorbrewer
    - r-rcurl
    - r-reshape2
    - r-rmarkdown
    - r-stringr
    - r-tidyr
    - r-venndiagram
    - r-vgam
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Analyze thermal proteome profiling (TPP) experiments'
  description: 'Analyze thermal proteome profiling (TPP) experiments with varying temperatures (TR) or compound concentrations (CCR).'

