{% set version = "1.0.1" %}

package:
  name: nanomath
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nanomath/nanomath-{{ version }}.tar.gz
  sha256: d402d672f9ff30952ec446a20db2a8e45f93c3487b708d6b0a481dc1ed0bacbc

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - pandas
    - numpy >1.8

test:
  imports:
    - nanomath

about:
  home: https://github.com/wdecoster/nanomath
  license: MIT License
  summary: 'A few simple math function for other Oxford Nanopore processing scripts'
  license_family: MIT
