{% set version = "3.28.1" %}
{% set name = "safe" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 5cde37cc8855612d372f2f5047a75c93acbe1d2273c07230a87c69a1778a3f91
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: GO.db, PFAM.db, reactome.db, hgu133a.db, breastCancerUPP, survival, foreach, doRNG, Rgraphviz, GOstats
requirements:
  host:
    - 'bioconductor-annotationdbi >=1.50.0,<1.51.0'
    - 'bioconductor-biobase >=2.48.0,<2.49.0'
    - r-base
    - r-sparsem
  run:
    - 'bioconductor-annotationdbi >=1.50.0,<1.51.0'
    - 'bioconductor-biobase >=2.48.0,<2.49.0'
    - r-base
    - r-sparsem
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'Significance Analysis of Function and Expression'
  description: 'SAFE is a resampling-based method for testing functional categories in gene expression experiments. SAFE can be applied to 2-sample and multi-class comparisons, or simple linear regressions. Other experimental designs can also be accommodated through user-defined functions.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
extra:
  identifiers:
    - biotools:safe
    - doi:10.1093/bioinformatics/bti260
  parent_recipe:
    name: bioconductor-safe
    path: recipes/bioconductor-safe
    version: 3.20.0

