{% set version = "1.12.4" %}
{% set name = "semisup" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 4d6bc649d62f20446ef5f7d1b647a38a7317214a675ee4f768d2d12c63097983
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: knitr, testthat, SummarizedExperiment
requirements:
  host:
    - r-base
    - r-vgam
  run:
    - r-base
    - r-vgam
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'Semi-Supervised Mixture Model'
  description: 'Implements a parametric semi-supervised mixture model. The permutation test detects markers with main or interactive effects, without distinguishing them. Possible applications include genome-wide association analysis and differential expression analysis.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
extra:
  parent_recipe:
    name: bioconductor-semisup
    path: recipes/bioconductor-semisup
    version: 1.4.0

