{% set version = "1.22.1" %}
{% set name = "GenomicTuples" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: b080704830853df95c1d7cf4e50cb180100e613acb96feedf02e6a4f1a836475
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: testthat, knitr, BiocStyle, rmarkdown
requirements:
  host:
    - 'bioconductor-biocgenerics >=0.34.0,<0.35.0'
    - 'bioconductor-genomeinfodb >=1.24.0,<1.25.0'
    - 'bioconductor-genomicranges >=1.40.0,<1.41.0'
    - 'bioconductor-iranges >=2.22.0,<2.23.0'
    - 'bioconductor-s4vectors >=0.26.0,<0.27.0'
    - r-base
    - r-data.table
    - 'r-rcpp >=0.11.2'
    - libblas
    - liblapack
  run:
    - 'bioconductor-biocgenerics >=0.34.0,<0.35.0'
    - 'bioconductor-genomeinfodb >=1.24.0,<1.25.0'
    - 'bioconductor-genomicranges >=1.40.0,<1.41.0'
    - 'bioconductor-iranges >=2.22.0,<2.23.0'
    - 'bioconductor-s4vectors >=0.26.0,<0.27.0'
    - r-base
    - r-data.table
    - 'r-rcpp >=0.11.2'
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Representation and Manipulation of Genomic Tuples'
  description: 'GenomicTuples defines general purpose containers for storing genomic tuples. It aims to provide functionality for tuples of genomic co-ordinates that are analogous to those available for genomic ranges in the GenomicRanges Bioconductor package.'
extra:
  identifiers:
    - biotools:genomictuples
    - doi:10.21105/joss.00020
  parent_recipe:
    name: bioconductor-genomictuples
    path: recipes/bioconductor-genomictuples
    version: 1.14.1

