{% set version = "1.31.0" %}
{% set name = "facsDorit" %}
{% set bioc = "3.12" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: a85f7c87e1254107fe8563199501ef4c
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
requirements:
  host:
    - 'bioconductor-prada >=1.66.0,<1.67.0'
    - r-base
  run:
    - 'bioconductor-prada >=1.66.0,<1.67.0'
    - r-base
    - curl
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: GPL-2
  summary: 'DKFZ FACS example data'
  description: 'FACS example data for cell-based assays. This data is used in the examples and vignettes of the package prada.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

