{% set version = "2.30.0" %}
{% set name = "RchyOptimyx" %}
{% set bioc = "3.12" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 8777fb50d67a67cdaafd77081320545a
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: flowCore
requirements:
  host:
    - 'bioconductor-flowtype >=2.28.0,<2.29.0'
    - 'bioconductor-graph >=1.68.0,<1.69.0'
    - 'bioconductor-rgraphviz >=2.34.0,<2.35.0'
    - r-base
    - r-sfsmisc
    - libblas
    - liblapack
  run:
    - 'bioconductor-flowtype >=2.28.0,<2.29.0'
    - 'bioconductor-graph >=1.68.0,<1.69.0'
    - 'bioconductor-rgraphviz >=2.34.0,<2.35.0'
    - r-base
    - r-sfsmisc
  build:
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - xorg-libxfixes  # [linux]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - 'LD_LIBRARY_PATH="${BUILD_PREFIX}/x86_64-conda-linux-gnu/sysroot/usr/lib64:${BUILD_PREFIX}/lib" $R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Optimyzed Cellular Hierarchies for Flow Cytometry'
  description: 'Constructs a hierarchy of cells using flow cytometry for maximization of an external variable (e.g., a clinical outcome or a cytokine response).'
extra:
  container:
    extended-base: true

