{% set version = "1.17.0" %}
{% set name = "prostateCancerTaylor" %}
{% set bioc = "3.12" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 4f2598c738eca1bea49ad39fb09d3c93
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: GEOquery, org.Hs.eg.db
requirements:
  host:
    - 'bioconductor-biobase >=2.50.0,<2.51.0'
    - r-base
  run:
    - 'bioconductor-biobase >=2.50.0,<2.51.0'
    - r-base
    - curl
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Prostate Cancer Data'
  description: 'A Bioconductor data package for the Taylor et al (2010) dataset.'

