{% set version = "1.25.0" %}
{% set name = "hmyriB36" %}
{% set bioc = "3.12" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: e5de65695ec5f40f6840f4fc093cf63f
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: GGtools, illuminaHumanv1.db
requirements:
  host:
    - 'bioconductor-biobase >=2.50.0,<2.51.0'
    - 'bioconductor-ggbase >=3.52.0,<3.53.0'
    - r-base
  run:
    - 'bioconductor-biobase >=2.50.0,<2.51.0'
    - 'bioconductor-ggbase >=3.52.0,<3.53.0'
    - r-base
    - curl
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'YRI hapmap + expression (GENEVAR), Build 36, r23a genotypes'
  description: 'YRI hapmap + expression (GENEVAR), Build 36, r23a genotypes'

