{% set version = "1.0.8" %}
{% set name = "EnMCB" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 94c4ad3a1358be0f2267be17cf653d597a4125bedd5a02798100821e0661ba01
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: SummarizedExperiment, testthat, Biobase, rms, survminer, affycoretools, knitr, plotROC, prognosticROC
requirements:
  host:
    - 'bioconductor-illuminahumanmethylation450kanno.ilmn12.hg19 >=0.6.0,<0.7.0'
    - 'bioconductor-minfi >=1.34.0,<1.35.0'
    - r-base
    - r-doparallel
    - r-foreach
    - r-ggplot2
    - r-glmnet
    - r-survival
    - r-survivalroc
    - r-survivalsvm
  run:
    - 'bioconductor-illuminahumanmethylation450kanno.ilmn12.hg19 >=0.6.0,<0.7.0'
    - 'bioconductor-minfi >=1.34.0,<1.35.0'
    - r-base
    - r-doparallel
    - r-foreach
    - r-ggplot2
    - r-glmnet
    - r-survival
    - r-survivalroc
    - r-survivalsvm
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'Predicting Disease Progression Based on Methylation Correlated Blocks using Ensemble Models'
  description: 'Creation of the correlated blocks using DNA methylation profiles. A stacked ensemble of machine learning models, which combined the support vector machine and elastic-net regression model, can be constructed to predict disease progression.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

