{% set version = "1.6.0" %}
{% set name = "metagene2" %}
{% set bioc = "3.12" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  md5: fae1160afa140e16dd8e8e8efbb7a41c
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: BiocGenerics, RUnit, knitr, BiocStyle, rmarkdown
requirements:
  host:
    - 'bioconductor-biocparallel >=1.24.0,<1.25.0'
    - 'bioconductor-dbchip >=1.34.0,<1.35.0'
    - 'bioconductor-genomeinfodb >=1.26.0,<1.27.0'
    - 'bioconductor-genomicalignments >=1.26.0,<1.27.0'
    - 'bioconductor-genomicranges >=1.42.0,<1.43.0'
    - 'bioconductor-iranges >=2.24.0,<2.25.0'
    - 'bioconductor-rsamtools >=2.6.0,<2.7.0'
    - 'bioconductor-rtracklayer >=1.50.0,<1.51.0'
    - r-base
    - r-data.table
    - r-dplyr
    - r-ggplot2
    - r-magrittr
    - r-purrr
    - 'r-r6 >=2.0'
    - r-reshape2
  run:
    - 'bioconductor-biocparallel >=1.24.0,<1.25.0'
    - 'bioconductor-dbchip >=1.34.0,<1.35.0'
    - 'bioconductor-genomeinfodb >=1.26.0,<1.27.0'
    - 'bioconductor-genomicalignments >=1.26.0,<1.27.0'
    - 'bioconductor-genomicranges >=1.42.0,<1.43.0'
    - 'bioconductor-iranges >=2.24.0,<2.25.0'
    - 'bioconductor-rsamtools >=2.6.0,<2.7.0'
    - 'bioconductor-rtracklayer >=1.50.0,<1.51.0'
    - r-base
    - r-data.table
    - r-dplyr
    - r-ggplot2
    - r-magrittr
    - r-purrr
    - 'r-r6 >=2.0'
    - r-reshape2
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'A package to produce metagene plots'
  description: 'This package produces metagene plots to compare coverages of sequencing experiments at selected groups of genomic regions. It can be used for such analyses as assessing the binding of DNA-interacting proteins at promoter regions or surveying antisense transcription over the length of a gene. The metagene2 package can manage all aspects of the analysis, from normalization of coverages to plot facetting according to experimental metadata. Bootstraping analysis is used to provide confidence intervals of per-sample mean coverages.'

