{% set name = "gNALI" %}
{% set version = "1.0.0" %}
{% set sha256 = "f209080e2989731942b0954754020d333067162530e5d24609d55d429eb32fcf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/phac-nml/gnali/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  entry_points:
    - gnali = gnali.gnali:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pybiomart
    - numpy
    - pandas
    - pysam
    - filelock

test:
  imports:
    - gnali
  commands:
    - gnali --help

about:
  home: https://github.com/phac-nml/gnali
  license: Apache-2.0
  license_file: LICENSE.txt
  license_family: APACHE
  summary: "gNALI (gene nonessentiality and loss-of-function identifier) is a tool for finding PLoF gene variants."
  dev_url: https://github.com/phac-nml/gnali
