{% set version = "0.1.3" %}

package:
  name: ggd
  version: {{ version }}

source:
  url: https://github.com/gogetdata/ggd-cli/archive/v{{ version }}.tar.gz
  sha256: 60863c0ddb039b243ec235eb27865d4bc76970a3aaaefa4916e6006b39d1fd54 

build:
    number: 0
    noarch: python
    entry_points:
      - ggd = ggd.__main__:main
    script: "python -m pip install . --no-deps --ignore-installed -vv" 

requirements:
  host:
    - pip
    - python
  run:
    - check-sort-order>=0.0.7
    - conda>=4.8.2,<=4.8.3
    - cyvcf2
    - future
    - fuzzywuzzy
    - git
    - gitpython
    - gsort>=0.1.4
    - htslib
    - krb5
    - oyaml
    - pysam
    - pytest
    - pytest-socket
    - python
    - python-levenshtein
    - pyyaml
    - requests>=2.20.0
    - ripgrep
    - samtools
    - wget
    - zlib
test:
  commands:
    - ggd --version
    - ggd --help

about:
  home: https://github.com/gogetdata/ggd-cli
  docs: https://gogetdata.github.io/
  license: MIT
  summary: "GoGetData (GGD) is a genomic data managment system. It provide simple and reproducible access to a repository of genomic data. Simply put, it is 'Conda' for genomic data"

