{% set version = "2.5.2" %}

package:
  name: varlociraptor
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/varlociraptor/varlociraptor/archive/v{{ version }}.tar.gz
  sha256: 906c967ba408d5f921af2a227eb993642870bea2953f00262808b9c809a4f3be

requirements:
  build:
    - rust >=1.30
    - clangdev
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - gsl
    - libcblas
    - openssl
    - zlib
    - bzip2
    - xz
    - clangdev
    - blis
  run:
    - gsl
    - openssl
    - zlib
    - bzip2
    - xz
    - blis

test:
  commands:
    - varlociraptor -h

about:
  home: https://varlociraptor.github.io
  license: GPLv3
  license_family: GPL
  summary: Flexible, uncertainty-aware variant calling with parameter free filtration via FDR control.
