{% set version = "1.52.0" %}
{% set name = "PCpheno" %}
{% set bioc = "3.12" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 844d3b5800809f0ed059126a0616da03
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: KEGG.db, GO.db, org.Sc.sgd.db
requirements:
  host:
    - 'bioconductor-annotate >=1.68.0,<1.69.0'
    - 'bioconductor-annotationdbi >=1.52.0,<1.53.0'
    - 'bioconductor-biobase >=2.50.0,<2.51.0'
    - 'bioconductor-category >=2.56.0,<2.57.0'
    - 'bioconductor-go.db >=3.12.0,<3.13.0'
    - 'bioconductor-graph >=1.68.0,<1.69.0'
    - 'bioconductor-gseabase >=1.52.0,<1.53.0'
    - 'bioconductor-kegg.db >=3.2.0,<3.3.0'
    - 'bioconductor-ppidata >=0.27.0,<0.28.0'
    - 'bioconductor-ppistats >=1.56.0,<1.57.0'
    - 'bioconductor-scisi >=1.62.0,<1.63.0'
    - 'bioconductor-slgi >=1.50.0,<1.51.0'
    - r-base
  run:
    - 'bioconductor-annotate >=1.68.0,<1.69.0'
    - 'bioconductor-annotationdbi >=1.52.0,<1.53.0'
    - 'bioconductor-biobase >=2.50.0,<2.51.0'
    - 'bioconductor-category >=2.56.0,<2.57.0'
    - 'bioconductor-go.db >=3.12.0,<3.13.0'
    - 'bioconductor-graph >=1.68.0,<1.69.0'
    - 'bioconductor-gseabase >=1.52.0,<1.53.0'
    - 'bioconductor-kegg.db >=3.2.0,<3.3.0'
    - 'bioconductor-ppidata >=0.27.0,<0.28.0'
    - 'bioconductor-ppistats >=1.56.0,<1.57.0'
    - 'bioconductor-scisi >=1.62.0,<1.63.0'
    - 'bioconductor-slgi >=1.50.0,<1.51.0'
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Phenotypes and cellular organizational units'
  description: 'Tools to integrate, annotate, and link phenotypes to cellular organizational units such as protein complexes and pathways.'
extra:
  identifiers:
    - biotools:pcpheno
    - doi:10.1038/nmeth.3252
  parent_recipe:
    name: bioconductor-pcpheno
    path: recipes/bioconductor-pcpheno
    version: 1.42.0

