{% set version = "2.0.7" %}
{% set name = "cBioPortalData" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 938efd85394f2013982bde6d1f6f56453aa9cbfea1d21e5320c37e677f1c736c
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: BiocStyle, knitr
requirements:
  host:
    - 'bioconductor-anvil >=1.0.0,<1.1.0'
    - 'bioconductor-biocfilecache >=1.12.0,<1.13.0'
    - 'bioconductor-genomeinfodb >=1.24.0,<1.25.0'
    - 'bioconductor-genomicranges >=1.40.0,<1.41.0'
    - 'bioconductor-iranges >=2.22.0,<2.23.0'
    - 'bioconductor-multiassayexperiment >=1.14.0,<1.15.0'
    - 'bioconductor-raggedexperiment >=1.12.0,<1.13.0'
    - 'bioconductor-rtcgatoolbox >=2.18.0,<2.19.0'
    - 'bioconductor-s4vectors >=0.26.0,<0.27.0'
    - 'bioconductor-summarizedexperiment >=1.18.0,<1.19.0'
    - 'bioconductor-tcgautils >=1.8.0,<1.9.0'
    - r-base
    - r-digest
    - r-dplyr
    - r-httr
    - r-rappdirs
    - r-readr
    - r-tibble
    - r-tidyr
  run:
    - 'bioconductor-anvil >=1.0.0,<1.1.0'
    - 'bioconductor-biocfilecache >=1.12.0,<1.13.0'
    - 'bioconductor-genomeinfodb >=1.24.0,<1.25.0'
    - 'bioconductor-genomicranges >=1.40.0,<1.41.0'
    - 'bioconductor-iranges >=2.22.0,<2.23.0'
    - 'bioconductor-multiassayexperiment >=1.14.0,<1.15.0'
    - 'bioconductor-raggedexperiment >=1.12.0,<1.13.0'
    - 'bioconductor-rtcgatoolbox >=2.18.0,<2.19.0'
    - 'bioconductor-s4vectors >=0.26.0,<0.27.0'
    - 'bioconductor-summarizedexperiment >=1.18.0,<1.19.0'
    - 'bioconductor-tcgautils >=1.8.0,<1.9.0'
    - r-base
    - r-digest
    - r-dplyr
    - r-httr
    - r-rappdirs
    - r-readr
    - r-tibble
    - r-tidyr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: AGPL-3
  summary: 'Exposes and makes available data from the cBioPortal web resources'
  description: 'The cBioPortalData package takes compressed resources from repositories such as cBioPortal and assembles a MultiAssayExperiment object with Bioconductor classes.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/AGPL-3'

