{% set version = "1.16.0" %}
{% set name = "DEsubs" %}
{% set bioc = "3.12" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 57b57e89981a95287f8424ca0ae2fde9
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: RUnit, BiocGenerics, knitr
requirements:
  host:
    - 'bioconductor-deseq >=1.42.0,<1.43.0'
    - 'bioconductor-deseq2 >=1.30.0,<1.31.0'
    - 'bioconductor-ebseq >=1.30.0,<1.31.0'
    - 'bioconductor-edger >=3.32.0,<3.33.0'
    - 'bioconductor-graph >=1.68.0,<1.69.0'
    - 'bioconductor-limma >=3.46.0,<3.47.0'
    - 'bioconductor-rbgl >=1.66.0,<1.67.0'
    - r-base
    - r-circlize
    - r-ggplot2
    - r-igraph
    - r-jsonlite
    - r-locfit
    - r-matrix
    - r-nbpseq
    - r-pheatmap
  run:
    - 'bioconductor-deseq >=1.42.0,<1.43.0'
    - 'bioconductor-deseq2 >=1.30.0,<1.31.0'
    - 'bioconductor-ebseq >=1.30.0,<1.31.0'
    - 'bioconductor-edger >=3.32.0,<3.33.0'
    - 'bioconductor-graph >=1.68.0,<1.69.0'
    - 'bioconductor-limma >=3.46.0,<3.47.0'
    - 'bioconductor-rbgl >=1.66.0,<1.67.0'
    - r-base
    - r-circlize
    - r-ggplot2
    - r-igraph
    - r-jsonlite
    - r-locfit
    - r-matrix
    - r-nbpseq
    - r-pheatmap
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'DEsubs: an R package for flexible identification of differentially expressed subpathways using RNA-seq expression experiments'
  description: 'DEsubs is a network-based systems biology package that extracts disease-perturbed subpathways within a pathway network as recorded by RNA-seq experiments. It contains an extensive and customizable framework covering a broad range of operation modes at all stages of the subpathway analysis, enabling a case-specific approach. The operation modes refer to the pathway network construction and processing, the subpathway extraction, visualization and enrichment analysis with regard to various biological and pharmacological features. Its capabilities render it a tool-guide for both the modeler and experimentalist for the identification of more robust systems-level biomarkers for complex diseases.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

