{% set version = "1.34.0" %}
{% set name = "DBChIP" %}
{% set bioc = "3.12" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: baf9d92ba43a3ec41d4491a7edf87d3d
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: ShortRead, BiocGenerics
requirements:
  host:
    - 'bioconductor-deseq >=1.42.0,<1.43.0'
    - 'bioconductor-edger >=3.32.0,<3.33.0'
    - r-base
  run:
    - 'bioconductor-deseq >=1.42.0,<1.43.0'
    - 'bioconductor-edger >=3.32.0,<3.33.0'
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'Differential Binding of Transcription Factor with ChIP-seq'
  description: 'DBChIP detects differentially bound sharp binding sites across multiple conditions, with or without matching control samples.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
extra:
  parent_recipe:
    name: bioconductor-dbchip
    path: recipes/bioconductor-dbchip
    version: 1.24.0

