{% set version = "1.0.2" %}
{% set name = "basilisk" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: c4fc4b3e941dfeca14ef94eb71ef55a5a2d6f586abc43a1351d933d198618998
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: knitr, rmarkdown, BiocStyle, testthat, callr
requirements:
  host:
    - 'bioconductor-basilisk.utils >=1.0.0,<1.1.0'
    - r-base
    - r-reticulate
  run:
    - 'bioconductor-basilisk.utils >=1.0.0,<1.1.0'
    - r-base
    - r-reticulate
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'Freezing Python Versions Inside Bioconductor Packages'
  description: 'Installs a self-contained Python instance that is managed by the R installation. This aims to provide a consistent Python version that can be used reliably by Bioconductor packages. Module versions are also controlled to guarantee consistent behavior on different user systems.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

