{% set version = "1.22.0" %}
{% set name = "MEIGOR" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 88b35f9d515d7f1d2abc51da644fa638b0b357f6e8d4eb8cbe6ab3a18611dd54
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: CellNOptR
requirements:
  host:
    - 'bioconductor-cnorode >=1.30.0,<1.31.0'
    - r-base
    - r-desolve
    - r-rsolnp
    - r-snowfall
  run:
    - 'bioconductor-cnorode >=1.30.0,<1.31.0'
    - r-base
    - r-desolve
    - r-rsolnp
    - r-snowfall
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'MEIGO - MEtaheuristics for bIoinformatics Global Optimization'
  description: 'Global Optimization'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
extra:
  identifiers:
    - biotools:meigor
    - doi:10.1186/1471-2105-15-136
  parent_recipe:
    name: bioconductor-meigor
    path: recipes/bioconductor-meigor
    version: 1.14.0

