{% set version = "1.40.0" %}
{% set name = "ArrayExpressHTS" %}
{% set bioc = "3.12" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 2c15364d9346d886e44a2be87173f584
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# SystemRequirements: GNU make
requirements:
  host:
    - 'bioconductor-biobase >=2.50.0,<2.51.0'
    - 'bioconductor-biocgenerics >=0.36.0,<0.37.0'
    - 'bioconductor-biomart >=2.46.0,<2.47.0'
    - 'bioconductor-biostrings >=2.58.0,<2.59.0'
    - 'bioconductor-deseq >=1.42.0,<1.43.0'
    - 'bioconductor-edger >=3.32.0,<3.33.0'
    - 'bioconductor-genomicranges >=1.42.0,<1.43.0'
    - 'bioconductor-iranges >=2.24.0,<2.25.0'
    - 'bioconductor-rhtslib >=1.22.0,<1.23.0'
    - 'bioconductor-rsamtools >=2.6.0,<2.7.0'
    - 'bioconductor-shortread >=1.48.0,<1.49.0'
    - r-base
    - r-bitops
    - r-hmisc
    - r-r2html
    - r-rcolorbrewer
    - r-rjava
    - r-sampling
    - r-sendmailr
    - r-snow
    - r-svmisc
    - r-xml
    - libblas
    - liblapack
  run:
    - 'bioconductor-biobase >=2.50.0,<2.51.0'
    - 'bioconductor-biocgenerics >=0.36.0,<0.37.0'
    - 'bioconductor-biomart >=2.46.0,<2.47.0'
    - 'bioconductor-biostrings >=2.58.0,<2.59.0'
    - 'bioconductor-deseq >=1.42.0,<1.43.0'
    - 'bioconductor-edger >=3.32.0,<3.33.0'
    - 'bioconductor-genomicranges >=1.42.0,<1.43.0'
    - 'bioconductor-iranges >=2.24.0,<2.25.0'
    - 'bioconductor-rhtslib >=1.22.0,<1.23.0'
    - 'bioconductor-rsamtools >=2.6.0,<2.7.0'
    - 'bioconductor-shortread >=1.48.0,<1.49.0'
    - r-base
    - r-bitops
    - r-hmisc
    - r-r2html
    - r-rcolorbrewer
    - r-rjava
    - r-sampling
    - r-sendmailr
    - r-snow
    - r-svmisc
    - r-xml
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'Artistic License 2.0'
  summary: 'ArrayExpress High Throughput Sequencing Processing Pipeline'
  description: 'RNA-Seq processing pipeline for public ArrayExpress experiments or local datasets'

