{% set version = "1.7.0" %}
{% set name = "qPLEXdata" %}
{% set bioc = "3.12" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: bca24b4388e0eefa00ab39ac152593e4
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
requirements:
  host:
    - 'bioconductor-msnbase >=2.16.0,<2.17.0'
    - 'bioconductor-qplexanalyzer >=1.8.0,<1.9.0'
    - r-base
    - r-dplyr
    - r-knitr
  run:
    - 'bioconductor-msnbase >=2.16.0,<2.17.0'
    - 'bioconductor-qplexanalyzer >=1.8.0,<1.9.0'
    - r-base
    - r-dplyr
    - r-knitr
    - curl
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: GPL-2
  summary: 'Data accompanying qPLEXanalyzer package'
  description: 'qPLEX-RIME and Full proteome TMT mass spectrometry datasets.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

