{% set version = "2.0.5" %}
{% set name = "PharmacoGx" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 1109bb8524d3cfc86d95615295b5389e03f3bd1dd4414ea81de3aec49b31aca3
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: pander, rmarkdown, knitr, knitcitations
requirements:
  host:
    - 'bioconductor-biobase >=2.48.0,<2.49.0'
    - 'bioconductor-biocparallel >=1.22.0,<1.23.0'
    - 'bioconductor-coregx >=1.0.0,<1.1.0'
    - 'bioconductor-s4vectors >=0.26.0,<0.27.0'
    - 'bioconductor-summarizedexperiment >=1.18.0,<1.19.0'
    - r-base
    - r-catools
    - r-downloader
    - r-ggplot2
    - r-jsonlite
    - r-magicaxis
    - r-rcolorbrewer
    - r-reshape2
    - r-testthat
  run:
    - 'bioconductor-biobase >=2.48.0,<2.49.0'
    - 'bioconductor-biocparallel >=1.22.0,<1.23.0'
    - 'bioconductor-coregx >=1.0.0,<1.1.0'
    - 'bioconductor-s4vectors >=0.26.0,<0.27.0'
    - 'bioconductor-summarizedexperiment >=1.18.0,<1.19.0'
    - r-base
    - r-catools
    - r-downloader
    - r-ggplot2
    - r-jsonlite
    - r-magicaxis
    - r-rcolorbrewer
    - r-reshape2
    - r-testthat
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Analysis of Large-Scale Pharmacogenomic Data'
  description: 'Contains a set of functions to perform large-scale analysis of pharmacogenomic data.'

