{% set version = "1.7.0" %}
{% set name = "tcgaWGBSData.hg19" %}
{% set bioc = "3.12" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: c6ec2a35996c09bacc7a2ece5b4bd3d1
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
requirements:
  host:
    - 'bioconductor-bsseq >=1.26.0,<1.27.0'
    - 'bioconductor-experimenthub >=1.16.0,<1.17.0'
    - r-base
    - r-knitr
  run:
    - 'bioconductor-bsseq >=1.26.0,<1.27.0'
    - 'bioconductor-experimenthub >=1.16.0,<1.17.0'
    - r-base
    - r-knitr
    - curl
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: GPL-2
  summary: Data
  description: 'Data package for WGBS Data in TCGA. Data is stored as SummarizedExperiment Format. See vignette on how to extract the data and perform differential methylation analysis.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

