{% set version = "1.4.1" %}
{% set name = "TPP2D" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 87d0105b26e1c1e4c4bdbd2b185bce3b266bb0ac9dacade1b574952eb205e964
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: knitr, testthat
requirements:
  host:
    - 'bioconductor-biocparallel >=1.22.0,<1.23.0'
    - 'bioconductor-limma >=3.44.0,<3.45.0'
    - r-base
    - r-doparallel
    - r-dplyr
    - r-foreach
    - r-ggplot2
    - r-mass
    - r-openxlsx
    - r-rcurl
    - r-stringr
    - r-tidyr
  run:
    - 'bioconductor-biocparallel >=1.22.0,<1.23.0'
    - 'bioconductor-limma >=3.44.0,<3.45.0'
    - r-base
    - r-doparallel
    - r-dplyr
    - r-foreach
    - r-ggplot2
    - r-mass
    - r-openxlsx
    - r-rcurl
    - r-stringr
    - r-tidyr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'Detection of ligand-protein interactions from 2D thermal profiles (DLPTP)'
  description: 'Detection of ligand-protein interactions from 2D thermal profiles (DLPTP), Performs an FDR-controlled analysis of 2D-TPP experiments by functional analysis of dose-response curves across temperatures.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

