{% set version = "1.24.0" %}
{% set name = "GeneOverlap" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 2a3148069d8b57234134076cc1e70d6eb6662c8b066e698572132c6feef420e5
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: RUnit, BiocGenerics, BiocStyle
requirements:
  host:
    - r-base
    - r-gplots
    - r-rcolorbrewer
  run:
    - r-base
    - r-gplots
    - r-rcolorbrewer
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'Test and visualize gene overlaps'
  description: 'Test two sets of gene lists and visualize the results.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
extra:
  identifiers:
    - biotools:geneoverlap
    - doi:10.1167/iovs.16-20618
  parent_recipe:
    name: bioconductor-geneoverlap
    path: recipes/bioconductor-geneoverlap
    version: 1.16.0

