{% set version = "1.2.0" %}
{% set name = "cmapR" %}
{% set bioc = "3.12" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 71ea04b26d5864408aa9c735b0a0cc78
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: knitr, testthat, BiocStyle
requirements:
  host:
    - 'bioconductor-prada >=1.66.0,<1.67.0'
    - 'bioconductor-rhdf5 >=2.34.0,<2.35.0'
    - 'bioconductor-summarizedexperiment >=1.20.0,<1.21.0'
    - r-base
    - r-data.table
    - r-matrixstats
  run:
    - 'bioconductor-prada >=1.66.0,<1.67.0'
    - 'bioconductor-rhdf5 >=2.34.0,<2.35.0'
    - 'bioconductor-summarizedexperiment >=1.20.0,<1.21.0'
    - r-base
    - r-data.table
    - r-matrixstats
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'file LICENSE'
  summary: 'CMap Tools in R'
  description: 'The Connectivity Map (CMap) is a massive resource of perturbational gene expression profiles built by researchers at the Broad Institute and funded by the NIH Library of Integrated Network-Based Cellular Signatures (LINCS) program. Please visit https://clue.io for more information. The cmapR package implements methods to parse, manipulate, and write common (CMap) data objects, such as annotated matrices and collections of gene sets.'
  license_file: LICENSE

