{% set name = "perl-text-csv_xs" %}
{% set version = "1.44" %}
{% set sha256 = "c4812ddca8e2654736c44bc2ce60b27a428a1bc4d5364b0ed1fad3609c8f9bc4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/H/HM/HMBRAND/Text-CSV_XS-1.44.tgz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - perl
    - perl-extutils-makemaker
    - perl-test-harness
    - perl-text-csv

  run:
    - perl
    - perl-test-harness
    - perl-text-csv

test:
  imports:
    - Text::CSV_XS

about:
  home: https://metacpan.org/pod/Text::CSV_XS
  license: perl_5
  summary: 'Text::CSV_XS - comma-separated values manipulation routines'
