{% set name = "perl-text-csv_xs" %}
{% set version = "1.43" %}
{% set sha256 = "cd94538e8ae9388d9e9e5527630f38f4d2b766e30310d283f0f9c692b94230bb" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/H/HM/HMBRAND/Text-CSV_XS-1.43.tgz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - perl
    - perl-extutils-makemaker
    - perl-test-harness
    - perl-text-csv

  run:
    - perl
    - perl-test-harness
    - perl-text-csv

test:
  imports:
    - Text::CSV_XS

about:
  home: https://metacpan.org/pod/Text::CSV_XS
  license: perl_5
  summary: 'Text::CSV_XS - comma-separated values manipulation routines'
