{% set version = "5.25.3" %}
{% set name = "GGtools" %}
{% set bioc = "3.12" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 7fca8396df9e29321d6663c04d51cb04
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: GGdata, illuminaHumanv1.db, SNPlocs.Hsapiens.dbSNP144.GRCh37, multtest, aod, rmeta
requirements:
  host:
    - 'bioconductor-annotationdbi >=1.52.0,<1.53.0'
    - 'bioconductor-biobase >=2.50.0,<2.51.0'
    - 'bioconductor-biocgenerics >=0.36.0,<0.37.0'
    - 'bioconductor-biostrings >=2.58.0,<2.59.0'
    - 'bioconductor-genomeinfodb >=1.26.0,<1.27.0'
    - 'bioconductor-genomicranges >=1.42.0,<1.43.0'
    - 'bioconductor-ggbase >=3.52.0,<3.53.0'
    - 'bioconductor-gviz >=1.34.0,<1.35.0'
    - 'bioconductor-homo.sapiens >=1.3.0,<1.4.0'
    - 'bioconductor-iranges >=2.24.0,<2.25.0'
    - 'bioconductor-rsamtools >=2.6.0,<2.7.0'
    - 'bioconductor-rtracklayer >=1.50.0,<1.51.0'
    - 'bioconductor-s4vectors >=0.28.0,<0.29.0'
    - 'bioconductor-snpstats >=1.40.0,<1.41.0'
    - 'bioconductor-variantannotation >=1.36.0,<1.37.0'
    - r-base
    - r-biglm
    - r-bit
    - r-data.table
    - r-ff
    - r-ggplot2
    - r-hexbin
    - r-iterators
    - r-reshape2
    - r-rocr
  run:
    - 'bioconductor-annotationdbi >=1.52.0,<1.53.0'
    - 'bioconductor-biobase >=2.50.0,<2.51.0'
    - 'bioconductor-biocgenerics >=0.36.0,<0.37.0'
    - 'bioconductor-biostrings >=2.58.0,<2.59.0'
    - 'bioconductor-genomeinfodb >=1.26.0,<1.27.0'
    - 'bioconductor-genomicranges >=1.42.0,<1.43.0'
    - 'bioconductor-ggbase >=3.52.0,<3.53.0'
    - 'bioconductor-gviz >=1.34.0,<1.35.0'
    - 'bioconductor-homo.sapiens >=1.3.0,<1.4.0'
    - 'bioconductor-iranges >=2.24.0,<2.25.0'
    - 'bioconductor-rsamtools >=2.6.0,<2.7.0'
    - 'bioconductor-rtracklayer >=1.50.0,<1.51.0'
    - 'bioconductor-s4vectors >=0.28.0,<0.29.0'
    - 'bioconductor-snpstats >=1.40.0,<1.41.0'
    - 'bioconductor-variantannotation >=1.36.0,<1.37.0'
    - r-base
    - r-biglm
    - r-bit
    - r-data.table
    - r-ff
    - r-ggplot2
    - r-hexbin
    - r-iterators
    - r-reshape2
    - r-rocr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'software and data for analyses in genetics of gene expression'
  description: 'software and data for analyses in genetics of gene expression and/or DNA methylation'
extra:
  identifiers:
    - biotools:ggtools
  parent_recipe:
    name: bioconductor-ggtools
    path: recipes/bioconductor-ggtools
    version: 5.16.0

