{% set version = "1.0.1" %}
{% set name = "ExploreModelMatrix" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 1b84c31de1d138aedc216133e76e2063c0c70307058b7ebbbac918ec60487ed0
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: testthat (>= 2.1.0), knitr, rmarkdown, htmltools, BiocStyle
requirements:
  host:
    - 'bioconductor-limma >=3.44.0,<3.45.0'
    - 'bioconductor-s4vectors >=0.26.0,<0.27.0'
    - r-base
    - r-cowplot
    - r-dplyr
    - r-dt
    - r-ggplot2
    - r-magrittr
    - r-mass
    - r-rintrojs
    - r-scales
    - r-shiny
    - r-shinydashboard
    - r-tibble
    - r-tidyr
  run:
    - 'bioconductor-limma >=3.44.0,<3.45.0'
    - 'bioconductor-s4vectors >=0.26.0,<0.27.0'
    - r-base
    - r-cowplot
    - r-dplyr
    - r-dt
    - r-ggplot2
    - r-magrittr
    - r-mass
    - r-rintrojs
    - r-scales
    - r-shiny
    - r-shinydashboard
    - r-tibble
    - r-tidyr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'MIT + file LICENSE'
  summary: 'Graphical Exploration of Design Matrices'
  description: 'Given a sample data table and a design formula, generate an interactive application to explore the resulting design matrix.'
  license_file: LICENSE

