{% set version = "1.3.3" %}
{% set name = "MouseGastrulationData" %}
{% set bioc = "3.12" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: ab384f4b6924f7845ce57be664b084dd
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: BiocStyle, knitr, rmarkdown
requirements:
  host:
    - 'bioconductor-biocgenerics >=0.36.0,<0.37.0'
    - 'bioconductor-experimenthub >=1.16.0,<1.17.0'
    - 'bioconductor-s4vectors >=0.28.0,<0.29.0'
    - 'bioconductor-singlecellexperiment >=1.12.0,<1.13.0'
    - 'bioconductor-summarizedexperiment >=1.20.0,<1.21.0'
    - r-base
  run:
    - 'bioconductor-biocgenerics >=0.36.0,<0.37.0'
    - 'bioconductor-experimenthub >=1.16.0,<1.17.0'
    - 'bioconductor-s4vectors >=0.28.0,<0.29.0'
    - 'bioconductor-singlecellexperiment >=1.12.0,<1.13.0'
    - 'bioconductor-summarizedexperiment >=1.20.0,<1.21.0'
    - r-base
    - curl
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: GPL-3
  summary: 'Single-Cell Transcriptomics Data across Mouse Gastrulation and Early Organogenesis'
  description: 'Provides processed and raw count matrices for single-cell RNA sequencing data from a timecourse of mouse gastrulation and early organogenesis.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

