{% set version = "1.10.1" %}
{% set name = "DelayedMatrixStats" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: bd3767b09c38b0dd0ae4febf426e1570b433d91afb7c792a8057909f4155da10
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: testthat, knitr, rmarkdown, covr, BiocStyle, microbenchmark, profmem
requirements:
  host:
    - 'bioconductor-biocparallel >=1.22.0,<1.23.0'
    - 'bioconductor-delayedarray >=0.14.0,<0.15.0'
    - 'bioconductor-hdf5array >=1.16.0,<1.17.0'
    - 'bioconductor-iranges >=2.22.0,<2.23.0'
    - 'bioconductor-s4vectors >=0.26.0,<0.27.0'
    - r-base
    - r-matrix
    - 'r-matrixstats >=0.56.0'
  run:
    - 'bioconductor-biocparallel >=1.22.0,<1.23.0'
    - 'bioconductor-delayedarray >=0.14.0,<0.15.0'
    - 'bioconductor-hdf5array >=1.16.0,<1.17.0'
    - 'bioconductor-iranges >=2.22.0,<2.23.0'
    - 'bioconductor-s4vectors >=0.26.0,<0.27.0'
    - r-base
    - r-matrix
    - 'r-matrixstats >=0.56.0'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'MIT + file LICENSE'
  summary: 'Functions that Apply to Rows and Columns of ''DelayedMatrix'' Objects'
  description: 'A port of the ''matrixStats'' API for use with DelayedMatrix objects from the ''DelayedArray'' package. High-performing functions operating on rows and columns of DelayedMatrix objects, e.g. col / rowMedians(), col / rowRanks(), and col / rowSds(). Functions optimized per data type and for subsetted calculations such that both memory usage and processing time is minimized.'
  license_file: LICENSE
extra:
  parent_recipe:
    name: bioconductor-delayedmatrixstats
    path: recipes/bioconductor-delayedmatrixstats
    version: 1.2.0

