{% set version = "1.60.1" %}
{% set name = "OrderedList" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 43388804be8485e941177945225dfa2cbfd70efa11f4ba63dfd3f0b4bfd84fa2
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
requirements:
  host:
    - 'bioconductor-biobase >=2.48.0,<2.49.0'
    - 'bioconductor-twilight >=1.64.0,<1.65.0'
    - r-base
  run:
    - 'bioconductor-biobase >=2.48.0,<2.49.0'
    - 'bioconductor-twilight >=1.64.0,<1.65.0'
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'Similarities of Ordered Gene Lists'
  description: 'Detection of similarities between ordered lists of genes. Thereby, either simple lists can be compared or gene expression data can be used to deduce the lists. Significance of similarities is evaluated by shuffling lists or by resampling in microarray data, respectively.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
extra:
  identifiers:
    - biotools:orderedlist
    - doi:10.1093/bioinformatics/btl385
  parent_recipe:
    name: bioconductor-orderedlist
    path: recipes/bioconductor-orderedlist
    version: 1.52.0

