{% set name = "ThermoRawFileParser" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  noarch: generic
  script:
    - mkdir $PREFIX/bin
    - cp * $PREFIX/bin
    - cp $RECIPE_DIR/ThermoRawFileParser.sh $PREFIX/bin
    - chmod +x $PREFIX/bin/ThermoRawFileParser.sh
    - ln -s $PREFIX/bin/ThermoRawFileParser.sh $PREFIX/bin/ThermoRawFileParser
    - ln -s $PREFIX/bin/ThermoRawFileParser.sh $PREFIX/bin/thermorawfileparser

source:
  # downloading pre-compiled packages, msbuild is a hell to compile unter Linux
  url: https://github.com/compomics/ThermoRawFileParser/releases/download/v{{ version }}/ThermoRawFileParser.zip
  sha256: febcf00de5d395d2d1a3ae053964e6e853fbe3c9cb9e05ff51374bc571ea1a34

requirements:
  run:
    - mono >=5

test:
  commands:
    - ThermoRawFileParser.sh 2>&1 | grep metadata

about:
  home: https://github.com/compomics/ThermoRawFileParser
  license: Other
  license_file: LICENSE
  summary: Wrapper around the .net (C#) ThermoFisher ThermoRawFileReader library for running on Linux with mono
  dev_url: https://github.com/compomics/ThermoRawFileParser
  doc_url: https://github.com/compomics/ThermoRawFileParser/blob/master/README.md
