{% set version = "1.25.1" %}
{% set name = "pcaGoPromoter.Hs.hg19" %}
{% set bioc = "3.12" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: a0ab2f5c9719bc4afda3ddb97f377c4b
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
requirements:
  host:
    - r-base
  run:
    - r-base
    - curl
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'pcaGoPromoter.Hs.hg19 is a data package used by pcaGoPromoter'
  description: 'Contains the data for transciption factors analysis of organism Homo Sapiens with package pcaGoPromoter'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

