{% set version = "2.4.05" %}
{% set name = "maftools" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: cdf1f212bc8c9126cf755b39b6a2f7b2be4188bc1912c39d07bb61da87158df3
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: knitr, rmarkdown, BSgenome, Biostrings, NMF, mclust, berryFunctions
requirements:
  host:
    - r-base
    - r-data.table
    - r-rcolorbrewer
    - r-survival
  run:
    - r-base
    - r-data.table
    - r-rcolorbrewer
    - r-survival
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'MIT + file LICENSE'
  summary: 'Summarize, Analyze and Visualize MAF Files'
  description: 'Analyze and visualize Mutation Annotation Format (MAF) files from large scale sequencing studies. This package provides various functions to perform most commonly used analyses in cancer genomics and to create feature rich customizable visualzations with minimal effort.'
  license_file: LICENSE
extra:
  parent_recipe:
    name: bioconductor-maftools
    path: recipes/bioconductor-maftools
    version: 1.6.15

