{% set version = "2.54.0" %}
{% set name = "cellHTS2" %}
{% set bioc = "3.12" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 36893689f9ad1ae609e9dae0b3a906b4
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: ggplot2
requirements:
  host:
    - 'bioconductor-biobase >=2.50.0,<2.51.0'
    - 'bioconductor-biocgenerics >=0.36.0,<0.37.0'
    - 'bioconductor-category >=2.56.0,<2.57.0'
    - 'bioconductor-genefilter >=1.72.0,<1.73.0'
    - 'bioconductor-gseabase >=1.52.0,<1.53.0'
    - 'bioconductor-prada >=1.66.0,<1.67.0'
    - 'bioconductor-splots >=1.56.0,<1.57.0'
    - 'bioconductor-vsn >=3.58.0,<3.59.0'
    - r-base
    - r-hwriter
    - r-locfit
    - r-rcolorbrewer
  run:
    - 'bioconductor-biobase >=2.50.0,<2.51.0'
    - 'bioconductor-biocgenerics >=0.36.0,<0.37.0'
    - 'bioconductor-category >=2.56.0,<2.57.0'
    - 'bioconductor-genefilter >=1.72.0,<1.73.0'
    - 'bioconductor-gseabase >=1.52.0,<1.53.0'
    - 'bioconductor-prada >=1.66.0,<1.67.0'
    - 'bioconductor-splots >=1.56.0,<1.57.0'
    - 'bioconductor-vsn >=3.58.0,<3.59.0'
    - r-base
    - r-hwriter
    - r-locfit
    - r-rcolorbrewer
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Analysis of cell-based screens - revised version of cellHTS'
  description: 'This package provides tools for the analysis of high-throughput assays that were performed in microtitre plate formats (including but not limited to 384-well plates). The functionality includes data import and management, normalisation, quality assessment, replicate summarisation and statistical scoring. A webpage that provides a detailed graphical overview over the data and analysis results is produced. In our work, we have applied the package to RNAi screens on fly and human cells, and for screens of yeast libraries. See ?cellHTS2 for a brief introduction.'
extra:
  identifiers:
    - biotools:cellhts2
  parent_recipe:
    name: bioconductor-cellhts2
    path: recipes/bioconductor-cellhts2
    version: 2.44.0

