{% set version = "1.0.5" %}
{% set name = "CSSQ" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 8b6e45b535a12cbea9ad0dc7cd62878c42d6abf9d3a98d34dfd33a83a668906f
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: BiocStyle, knitr, rmarkdown
requirements:
  host:
    - 'bioconductor-genomicalignments >=1.24.0,<1.25.0'
    - 'bioconductor-genomicfeatures >=1.40.0,<1.41.0'
    - 'bioconductor-genomicranges >=1.40.0,<1.41.0'
    - 'bioconductor-iranges >=2.22.0,<2.23.0'
    - 'bioconductor-rsamtools >=2.4.0,<2.5.0'
    - 'bioconductor-rtracklayer >=1.48.0,<1.49.0'
    - 'bioconductor-s4vectors >=0.26.0,<0.27.0'
    - 'bioconductor-summarizedexperiment >=1.18.0,<1.19.0'
    - r-base
    - r-ggplot2
  run:
    - 'bioconductor-genomicalignments >=1.24.0,<1.25.0'
    - 'bioconductor-genomicfeatures >=1.40.0,<1.41.0'
    - 'bioconductor-genomicranges >=1.40.0,<1.41.0'
    - 'bioconductor-iranges >=2.22.0,<2.23.0'
    - 'bioconductor-rsamtools >=2.4.0,<2.5.0'
    - 'bioconductor-rtracklayer >=1.48.0,<1.49.0'
    - 'bioconductor-s4vectors >=0.26.0,<0.27.0'
    - 'bioconductor-summarizedexperiment >=1.18.0,<1.19.0'
    - r-base
    - r-ggplot2
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Chip-seq Signal Quantifier Pipeline'
  description: 'This package is desgined to perform statistical analysis to identify statistically significant differentially bound regions between multiple groups of ChIP-seq dataset.'

