package:
  name: preseq
  version: 3.1.1

source:
  url: https://github.com/smithlabcode/preseq/releases/download/v3.1.1/preseq-3.1.1.tar.gz
  sha256: 61abe8ca599e7f3b99241de8b6875cf8bb5e09c04f82eb043da9688d51347fb5
  patches: Makefile.patch

build:
  number: 0
  skip: True  # [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - zlib
    - gsl
    - openblas
  run:
    - zlib
    - gsl
    - openblas

test:
  commands:
    - preseq
    - bam2mr

about:
  home: https://github.com/smithlabcode/preseq
  license: GNU GENERAL PUBLIC LICENSE
  summary: 'Software for predicting library complexity and genome coverage in high-throughput sequencing'
