package:
  name: preseq
  version: 3.1.0

source:
  url: https://github.com/smithlabcode/preseq/releases/download/v3.1.0/preseq-3.1.0.tar.gz
  sha256: 54e8a40020ae398fd8a15fdb005ece2e24ec03303773e2ce9703ebe263f8aa05
  patches: Makefile.patch

build:
  number: 0
  skip: True  # [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - zlib
    - gsl
    - openblas
  run:
    - zlib
    - gsl
    - openblas

test:
  commands:
    - preseq
    - bam2mr

about:
  home: https://github.com/smithlabcode/preseq
  license: GNU GENERAL PUBLIC LICENSE
  summary: 'Software for predicting library complexity and genome coverage in high-throughput sequencing'
