{% set version = "1.19.0" %}
{% set name = "Imetagene" %}
{% set bioc = "3.12" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 233f5e74a0e46a6ccf66e9c0bd390c2f
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: knitr, BiocStyle, rmarkdown
requirements:
  host:
    - 'bioconductor-metagene >=2.22.0,<2.23.0'
    - r-base
    - r-d3heatmap
    - r-ggplot2
    - r-shiny
    - r-shinybs
    - r-shinyfiles
    - r-shinythemes
  run:
    - 'bioconductor-metagene >=2.22.0,<2.23.0'
    - r-base
    - r-d3heatmap
    - r-ggplot2
    - r-shiny
    - r-shinybs
    - r-shinyfiles
    - r-shinythemes
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'Artistic-2.0 | file LICENSE'
  summary: 'A graphical interface for the metagene package'
  description: 'This package provide a graphical user interface to the metagene package. This will allow people with minimal R experience to easily complete metagene analysis.'
  license_file: LICENSE

